### PR TITLE
 kie-issues#44: DMN Editor: Autolayout is broken for decision services

### LINKED ISSUE #44: DMN Editor: Autolayout is broken for decision services
If user tries open diagram with decision services, without layout, the autolayout prepares a wrong layout.

What user gets:
image-2020-06-23-08-19-08-376

What is expected (not strictly, but it is organized at least semantically, the decision is in decision service):
image-2020-06-23-08-19-30-423

Used dmn model: [basicAdd.txt](https://github.com/kiegroup/kie-issues/files/10103516/basicAdd.txt)

### PR DESCRIPTION
**Pull request by danielzhe**
Closes https://github.com/kiegroup/kie-issues/issues/44

**What this PR does?**
When user opens a DMN diagram that does not have layout information (the DMNDI node), the automatic layout is performed using a heuristic to calculate a good position for the nodes.

Nodes inside DecisionServices should move with its parent and are ignored by the algorithm that considers only the position of the DecisionService. 

Now after the auto layout is performed the nodes inside the DecisionService are repositioned to be visible inside the DecisionService (to follow the position of the DecisionService).

**Test**
To test this PR, open a DMN diagram that does not have layout information (the DMNDI node) and have a DecisionService.

1. If the Decision inside DecisionService are encapsulatedDecision, it should be the bottom part (bellow the divider) of the DecisionService
2. If it is outputDecision, it should be in the top part (above the divider)

### CODE REVIEW

**Comment by danielzhe** [comment]
@jomarko and @yesamer : First blue PR.

File: packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java [hunk 1]
```diff
@@ -90,7 +90,7 @@ public DMNDiagramEditor(final View view,
                             final DecisionNavigatorDock decisionNavigatorDock,
                             final DiagramEditorPropertiesDock diagramPropertiesDock,
                             final PreviewDiagramDock diagramPreviewAndExplorerDock,
-                            final LayoutHelper layoutHelper,
+                            final @DMNEditor DMNLayoutHelper layoutHelper,
```
Comment (yesamer) [inline packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java:93]: @danielzhe I'm a bit confused here, this means we previously used the Default Layout Helper?

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/layout/LayoutHelper.java [hunk 2]
```diff
@@ -65,7 +65,4 @@ public boolean hasLayoutInformation(final Diagram diagram) {
         return layoutService.hasLayoutInformation(diagram.getGraph());
     }
 
-    public LayoutService getLayoutService() {
-        return this.layoutService;
-    }
```
Comment (yesamer) [inline packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/layout/LayoutHelper.java:70]: @danielzhe I suppose no one is actually calling this, but bear in mind that `layoutService` is private, so SubClasses can't access directly that field. 
In normal circumstances, I would suggest setting `layoutService` with `protected`, but up to you. I mean, I don't expect big changes here, so if you think `layoutService` will be used by its own class only, it's fine for me!

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/sugiyama/LayeredGraph.java [hunk 3]
```diff
@@ -102,6 +102,10 @@ public int getVertexHeight(final String vertexId) {
 
     @Override
     public int getVertexWidth(final String vertexId) {
+
+        // Retornar outro tamanho para DS
```
Comment (yesamer) [inline packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/sugiyama/LayeredGraph.java]: @danielzhe Typo?

**Review by yesamer — COMMENTED** [review]
@danielzhe Celebrating your first blue PR! 
A first round of code review:

File: packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java (hunk 1 above)
Comment (danielzhe) [reply packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java:93]: Yes.

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/layout/LayoutHelper.java (hunk 2 above)
Comment (danielzhe) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/layout/LayoutHelper.java:70]: Yes, it was not being used anywhere.

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/sugiyama/LayeredGraph.java (hunk 3 above)
Comment (danielzhe) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/sugiyama/LayeredGraph.java]: I think I forgot this comment I did to myself

File: packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java (hunk 1 above)
Comment (yesamer) [reply packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java:93]: Ok, thank you. So we had `DMNLayoutHelper` but we didn't use it. Weird.

**Comment by yesamer** [comment]
@danielzhe 

Error:    DMNBackwardCompatibilityIT.testDMN13Assets:42->runAssets:64->DMNDesignerBaseIT.executeDMNTestCase:207

**Comment by danielzhe** [comment]
> @danielzhe
> 
> Error: DMNBackwardCompatibilityIT.testDMN13Assets:42->runAssets:64->DMNDesignerBaseIT.executeDMNTestCase:207

It looks like I fixed another undocumented issue. This test was failing because now the DecisionService without layout information is correctly unmarshalled  -> marshalled with its inner nodes.
Tests fixed to reflect this change.

**Comment by tiagobento** [comment]
Alright... green build! Is this good to go? @yesamer @danielzhe

**Comment by yesamer** [comment]
Reviewing it...

File: packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/toolbar/DMNGraphProcessor.java [hunk 4]
```diff
@@ -40,27 +62,76 @@ public DMNGraphProcessor() {
...
-                // All edges that points to nodes inside DS now points to DS
-                for (final Node o : childNodes) {
-                    replacedNodes.put(o.getUUID(), n.getUUID());
-                }
-            }
-        }
+    void replaceDecisionServiceInnerNodes(final List<Node> nodes,
+                                          final String nodeUuid,
+                                          final DecisionService decisionService) {
+        final HashSet<String> innerIds = getInnerIds(decisionService);
```
Comment (jomarko) [inline packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/widgets/toolbar/DMNGraphProcessor.java]: Minor, however I think recommended practice is do declare variable `final Set<String> innerIds` instead of `final HashSet<String> innerIds` if we do not use some specific method of `HashSet`

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/sugiyama/SugiyamaLayoutService.java [hunk 5]
```diff
@@ -214,6 +227,95 @@ Layout buildLayout(final HashMap<String, Node> indexByUuid,
...
+//                    final Point2D parentBottomRight = parentPosition.get().getBottomRight();
+//
+//                    final Point2D ulChild = new Point2D(x,
+//                                                        DEFAULT_PARENT_NODE_HEIGHT / 2 + DEFAULT_INNER_VERTICAL_PADDING);
+//                    final Point2D brChild = new Point2D(ulChild.getX() + DEFAULT_VERTEX_WIDTH,
+//                                                        ulChild.getY() + DEFAULT_VERTEX_HEIGHT);
+//
+//                    final VertexPosition position = new VertexPositionImpl(childId,
+//                                                                           ulChild,
+//                                                                           brChild);
```
Comment (jomarko) [inline packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/sugiyama/SugiyamaLayoutService.java]: I think we can remove this?

**Review by jomarko — COMMENTED** [review]
Thank you for the first blue PR @danielzhe .

I was not able to check manually the effect of changes in this PR.

I built & start `kie-tools` as:
- `pnpm bootstrap`
- `pnpm -F online-editor... build:dev`
- `pnpm -F online-editor start`

However trying to open `basicAdd` model, I get

Screenshot 2023-03-13 110433

**Comment by danielzhe** [comment]
> Thank you for the first blue PR @danielzhe .
> 
> I was not able to check manually the effect of changes in this PR.
> 
> I built & start `kie-tools` as:
> 
> * `pnpm bootstrap`
> * `pnpm -F online-editor... build:dev`
> * `pnpm -F online-editor start`
> 
> However trying to open `basicAdd` model, I get
> 
> Screenshot 2023-03-13 110433

Can you provide this 'basicAdd' model that you used to test it?

**Comment by jomarko** [comment]
@danielzhe sure, see the last line of comment https://github.com/kiegroup/kie-issues/issues/44#issue-1466295405

**Comment by jomarko** [comment]
@danielzhe thank you, I was able to retest the PR manually once `.errai` folder deleted manually.

I found this issue. For the `basicAdd` model. when I I am opening it:
- I am prompted to proceed with computing or without computing layout, I choose I want to compute layout
- Then I see correct diagram [1]
- Now I close and reopen the `basicAdd`, previous 2 steps are repeated (prompted to confirm with or without layout, and correct autolayout computed - so far so good)
- Then I try to move some node, close and reopen `basicAdd`
- Now, unfortunately I do not see correct diagram [2]

[1]
Screenshot 2023-03-14 101341

[2]
Screenshot 2023-03-14 101413

**Comment by yesamer** [comment]
**Manual Testing**

Tested cases:
Screenshot 2023-03-15 at 13 48 28

Screenshot 2023-03-15 at 13 47 52

Screenshot 2023-03-15 at 13 49 29

Screenshot 2023-03-15 at 13 51 10

Screenshot 2023-03-15 at 13 52 45

Screenshot 2023-03-15 at 14 03 47

Screenshot 2023-03-15 at 14 07 30

Screenshot 2023-03-15 at 14 10 44

Screenshot 2023-03-15 at 14 12 34

**Comment by yesamer** [comment]
@danielzhe Excellent work! Before proceeding to the Code review, please address @jomarko reports.

**Comment by danielzhe** [comment]
@yesamer @jomarko Changes applied! Ready for review.

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/sugiyama/SugiyamaLayoutService.java [hunk 6]
```diff
@@ -214,6 +227,79 @@ Layout buildLayout(final HashMap<String, Node> indexByUuid,
...
+        return false;
+    }
+
+    boolean isXSet(final Bound bound) {
+        return bound.hasX() && !isCloseToZero(bound.getX());
+    }
+
+    boolean isYSet(final Bound bound) {
+        return bound.hasY() && !isCloseToZero(bound.getY());
+    }
```
Comment (jomarko) [inline packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/sugiyama/SugiyamaLayoutService.java:304]: Shouldn't be these some static methods in some util class as we repeat them in more java classes?

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/sugiyama/step04/DefaultVertexPositioning.java [hunk 7]
```diff
@@ -253,4 +270,64 @@ public void removeVirtualVertices(final List<OrientedEdge> edges,
...
+        return bound.hasX() && !isCloseToZero(bound.getX());
+    }
+
+    boolean isYSet(final Bound bound) {
+        return bound.hasY() && !isCloseToZero(bound.getY());
+    }
+
+    protected static boolean isCloseToZero(final double value) {
+        return Math.abs(value - 0) < CLOSE_TO_ZERO_TOLERANCE;
+    }
```
Comment (jomarko) [inline packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/sugiyama/step04/DefaultVertexPositioning.java:332]: see comment above

**Review by jomarko — APPROVED** [review]
@danielzhe thank you. I can confirm the reopening scenario works now perfectly. I am approving the PR, however, I think, we could reduce the codebase amount of lines a little bit. see my comment inline.

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/sugiyama/step04/DefaultVertexPositioning.java (hunk 7 above)
Comment (danielzhe) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/sugiyama/step04/DefaultVertexPositioning.java:332]: We can, but it's gonna be necessary to rewrite some tests, refactor the code and I think we have other priorities now. @jomarko 

Wdyt @yesamer ? It's also ready for your review.

**Review by tiagobento — APPROVED** [review]
