### PR TITLE
kie-issues#259: Make DMN Editor's Boxed Expression Editor Context Menu show only relevant operations for specific cells.

### LINKED ISSUE #259: Make DMN Editor's Boxed Expression Editor Context Menu show only relevant operations for specific cells
Take these historical notes into account when making this task:
-  Context Menu broken on DT top-level headers. Column index is broken. E.g. Add to the right/left.
-  "Additional row" context menu broken. Shouldn't have Delete nor Insert below. See Context <result> cells.
-  SELECTION Cut/paste/reset should not be available for header cells on Context Menu.
-  Logic type selector should never render outside the screen. Same for context menu.
-  Context Menu shouldn't be allowed on every cell. Fix it.
- Menu items 'Reset', 'Copy', 'Cut' and 'Paste' for header cells (header cells of columns, leading row cells of parameters, context entries, generally those containing name and data type) do not work, we should remove them
- Some places miss 'Duplicate row' option (Relation data cell, Relation row index cell, Invocation parameter header cell, Context entry header cell, List row index cell)

Please fix https://github.com/kiegroup/kie-issues/issues/324 as part of this issue too.

### Related issues
- https://github.com/kiegroup/kie-issues/issues/291

### PR DESCRIPTION
**Pull request by jomarko**
Closes https://github.com/kiegroup/kie-issues/issues/259

- We add an empty state in case no operations is avaliable for the selected cell
- We introduce `allowedOperations` per each expression type `LiteralExpression`, `DecisionTableExpression`, `RelationExpression` 
- We move 'copy' , 'cut', 'paste' and 'reset' commands from hardcoded in 'BeeTableContextMenuHandler' into particular expression types: `RelationExpression`, `DecisionTableExpression` ...
- We do not show `copy`, `cut`, `paste` and `reset` for Literal expression header cell
- We do not show `copy`, `cut`, `paste` and `reset` for context entries header cells, and top header cell, also `delete`, `insert below` and `duplicate` are disabled for `<result>` entry
- We do not show `copy`, `cut`, `paste` and `reset` for column header cells , row index cells, and hit policy selector cell
- We do not show `copy`, `cut`, `paste` and `reset` for column header cells and row index cells
- We align Invocation context menus with Relation and DecisionTable context menus
- We are very strict for Function expression, we allow only to reset feel expression function row
- We allow only `insert`, `delete` and `duplicate` for row index cells in List Expression

### CODE REVIEW

File: packages/boxed-expression-component/src/i18n/locales/en.ts [hunk 1]
```diff
@@ -81,6 +81,7 @@ export const en: BoxedExpressionEditorI18n = {
   methodSignature: "method signature",
   model: "model",
   name: "Name",
+  noOptionsAvailable: "No options available.",
```
Comment (tiagobento) [inline packages/boxed-expression-component/src/i18n/locales/en.ts]: Is this not being used? If this is an "empty state" for the context menu, I think it should be "No operations available."

File: packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx [hunk 2]
```diff
@@ -301,6 +311,61 @@ export function RelationExpression(relationExpression: RelationExpressionDefinit
...
+    reactTableInstanceRowsLength: number,
+    column: ReactTable.ColumnInstance<any> | undefined,
+    columns: ReactTable.ColumnInstance<any>[] | undefined
+  ) => BeeTableOperation[] = useCallback(
+    (
+      selectionStart: BeeTableSelectionActiveCell | undefined,
+      selectionEnd: BeeTableSelectionActiveCell | undefined,
+      reactTableInstanceRowsLength: number,
+      column: ReactTable.ColumnInstance<any> | undefined,
+      columns: ReactTable.ColumnInstance<any>[] | undefined
```
Comment (tiagobento) [inline packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx]: No need to redeclare the types here.

File: packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx [hunk 3]
```diff
@@ -301,6 +311,61 @@ export function RelationExpression(relationExpression: RelationExpressionDefinit
     return relationExpression.isNested ? BeeTableHeaderVisibility.LastLevel : BeeTableHeaderVisibility.AllLevels;
   }, [relationExpression.isNested]);
 
+  const allowedOperations: (
+    selectionStart: BeeTableSelectionActiveCell | undefined,
+    selectionEnd: BeeTableSelectionActiveCell | undefined,
+    reactTableInstanceRowsLength: number,
+    column: ReactTable.ColumnInstance<any> | undefined,
+    columns: ReactTable.ColumnInstance<any>[] | undefined
```
Comment (tiagobento) [inline packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx]: This could probably be extract to a type so we avoid duplicating the types of each parameter, and also prevent the confusion between the first two arguments that are of the same type.

File: packages/boxed-expression-component/src/expressions/ContextExpression/ContextExpression.tsx [hunk 4]
```diff
@@ -196,6 +201,16 @@ export function ContextExpression(contextExpression: ContextExpressionDefinition
           { name: i18n.rowOperations.insertAbove, type: BeeTableOperation.RowInsertAbove },
           { name: i18n.rowOperations.insertBelow, type: BeeTableOperation.RowInsertBelow },
           { name: i18n.rowOperations.delete, type: BeeTableOperation.RowDelete },
+          { name: i18n.rowOperations.delete, type: BeeTableOperation.RowDuplicate },
```
Comment (tiagobento) [inline packages/boxed-expression-component/src/expressions/ContextExpression/ContextExpression.tsx]: This should have the "Duplicate" label, no?

**Review by tiagobento — COMMENTED** [review]
I know this is in draft, but I was taking a look so... here are some comments :)

File: packages/boxed-expression-component/src/expressions/ContextExpression/ContextExpression.tsx (hunk 4 above)
Comment (jomarko) [reply packages/boxed-expression-component/src/expressions/ContextExpression/ContextExpression.tsx]: well spotted , fixing

File: packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx (hunk 3 above)
Comment (jomarko) [reply packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx]: good idea, will introduce a separate type

File: packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx (hunk 2 above)
Comment (jomarko) [reply packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx]: ok, I will try to remove them, not sure if it was not added automatically in some precommit hook, I will see.

File: packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx (hunk 3 above)
Comment (jomarko) [reply packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx]: @tiagobento for now, I just used `selection: BeeTableSelection` instead of `selectionStart` and `selectionEnd`

So with my latest changes `allowedOperations` still has 4 parameters. What is not ideal. Especially `column` and `columns` are used basically just for `Decision Table` expression.

What is you opinion about passing just `selection` - containing current selection start and selection end, and `reactTable Instance` - containing columns, rows length?

File: packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx [hunk 5]
```diff
@@ -91,13 +93,22 @@ export function DecisionTableExpression(
...
+        ],
+      },
     ],
     [i18n]
   );
 
   const beeTableOperationConfig = useMemo<BeeTableOperationConfig>(() => {
     const config: BeeTableOperationConfig = {};
-    config[""] = generateOperationConfig(i18n.inputClause);
+    config[""] = generateOperationConfig(i18n.outputClause);
```
Comment (jomarko) [inline packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx:111]: change due to https://github.com/kiegroup/kie-issues/issues/291

**Comment by tiagobento** [comment]
Oops.. conflict :D

File: packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx [hunk 6]
```diff
@@ -243,6 +236,22 @@ export function BeeTableContextMenuHandler({
...
+          console.info("Cuting");
+          break;
+        case BeeTableOperation.SelectionPaste:
+          paste();
+          console.info("Pasting");
+          break;
+        case BeeTableOperation.SelectionReset:
+          erase();
+          console.info("Reseting");
+          break;
```
Comment (tiagobento) [inline packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx]: Can we change those to `console.debug`? Perhaps with more information, even..

File: packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx [hunk 7]
```diff
@@ -271,6 +284,13 @@ export function BeeTableContextMenuHandler({
     };
   }, [xPos, yPos]);
 
+  const reactTableInstanceRowsLength = useMemo(() => {
+    return reactTableInstance.rows.length;
+  }, [reactTableInstance.rows.length]);
+
+  const currentAllowedOperations = allowedOperations(selection, reactTableInstanceRowsLength, column, columns);
+  const someOperationIsAllowed = allOperations.some((operation) => currentAllowedOperations.includes(operation.type));
```
Comment (tiagobento) [inline packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx]:
```suggestion
  const hasAllowedOperations = allOperations.some((operation) => currentAllowedOperations.includes(operation.type));
```

? :D

Comment (tiagobento) [inline packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx]: Any reason why we're not memoizing these values? This is very important to avoid unnecessary re-renders.

File: packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx [hunk 8]
```diff
@@ -271,6 +284,13 @@ export function BeeTableContextMenuHandler({
     };
   }, [xPos, yPos]);
 
+  const reactTableInstanceRowsLength = useMemo(() => {
+    return reactTableInstance.rows.length;
+  }, [reactTableInstance.rows.length]);
+
+  const currentAllowedOperations = allowedOperations(selection, reactTableInstanceRowsLength, column, columns);
```
Comment (tiagobento) [inline packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx]:
```suggestion
  const allowedOperationsForSelection = allowedOperations(selection, reactTableInstanceRowsLength, column, columns);
```

? :D

File: packages/unitables-dmn/src/DmnRunnerOutputsTable.tsx [hunk 9]
```diff
@@ -126,10 +129,37 @@ function OutputsBeeTable({ id, i18n, outputsPropertiesMap, results, scrollablePa
...
+      i18n.rowOperations.insertAbove,
+      i18n.rowOperations.insertBelow,
+      i18n.rowOperations.duplicate,
+      i18n.rowOperations.delete,
+      i18n.rowOperations.reset,
+      i18n.terms.selection,
+      i18n.terms.reset,
+      i18n.terms.copy,
+      i18n.terms.cut,
+      i18n.terms.paste,
```
Comment (tiagobento) [inline packages/unitables-dmn/src/DmnRunnerOutputsTable.tsx]: No need to have i18n so granular.. A simple `i18n` here would be enough.

File: packages/unitables-dmn/src/DmnRunnerOutputsTable.tsx [hunk 10]
```diff
@@ -372,9 +402,32 @@ function OutputsBeeTable({ id, i18n, outputsPropertiesMap, results, scrollablePa
     return row.original.id;
   }, []);
 
+  const allowedOperations = useCallback(
+    (
+      selection: BeeTableSelection,
+      reactTableInstanceRowsLength: number,
+      column: ReactTable.ColumnInstance<any> | undefined,
+      columns: ReactTable.ColumnInstance<any>[] | undefined
```
Comment (tiagobento) [inline packages/unitables-dmn/src/DmnRunnerOutputsTable.tsx]: Let's extract this to a type? Will look cleaner everywhere. These types are replicated all over the code.

File: packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx [hunk 11]
```diff
@@ -62,7 +75,12 @@ export function BeeTableContextMenuHandler({
   const { i18n } = useBoxedExpressionEditorI18n();
   const { setCurrentlyOpenContextMenu } = useBoxedExpressionEditor();
 
-  const { activeCell } = useBeeTableSelection();
+  const { activeCell, selectionStart, selectionEnd } = useBeeTableSelection();
+  const selection: BeeTableSelection = {
+    active: activeCell,
+    selectionStart: selectionStart,
+    selectionEnd: selectionEnd,
+  };
```
Comment (tiagobento) [inline packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx]: Wrap this in a `useMemo`.

**Review by tiagobento — CHANGES_REQUESTED** [review]
Nice job @jomarko @danielzhe! This PR looks really nice. As usual, left some comments inline :)

File: packages/unitables-dmn/src/DmnRunnerOutputsTable.tsx (hunk 10 above)
Comment (jomarko) [reply packages/unitables-dmn/src/DmnRunnerOutputsTable.tsx]: @tiagobento thank you for feedback. I incorporated it as:
- https://github.com/kiegroup/kie-tools/pull/1652/commits/ba2329206fc814caca28302e6336e71961c304f4

Furthermore, about introducing a a new type, I tried to simplify it even more, see:
- https://github.com/kiegroup/kie-tools/pull/1652/commits/3f423c6aec1f4837eb877a53c4264fc220c7121e

I thought I will be able to simplify `BeeTableContextMenuAllowedOperationsConditions` even more. I tried to remove `column` and `columns` from `BeeTableContextMenuAllowedOperationsConditions` and replace it in particual expressions with `beeTableColumns`, but I was not able to get it working. I think I miss some understanding of difference between `beeTableColumns` in `DecisionTableExpression` and `columns` in `beeTableContextMenuHandler`.

FYI, this PR currently assumes single cell is selected. Multiple cells selected scenarios are being covered by @danielzhe to cover fully kiegroup/kie-issues#168. However if it is fine to do it in separate PR, we can do it.

File: packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx (hunk 3 above)
Comment (tiagobento) [reply packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx]: @jomarko No need to simplify it even more. Let's revert it back to the stage where it was working, and we'll be good to go.

File: packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx [hunk 12]
```diff
@@ -293,6 +311,17 @@ export function BeeTableContextMenuHandler({
     }
   });
 
+  const allowedOperationsForSelection = useMemo(() => {
+    return allowedOperations({
+      selection,
+      column,
+      columns,
+    } as BeeTableContextMenuAllowedOperationsConditions);
```
Comment (tiagobento) [inline packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx]: You shouldn't need a cast here... Please double-check.

File: packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx (hunk 3 above)
Comment (jomarko) [reply packages/boxed-expression-component/src/expressions/RelationExpression/RelationExpression.tsx]: @tiagobento current state should be working, I can recheck during incorporating kiegroup/kie-issues#324

File: packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx (hunk 12 above)
Comment (jomarko) [reply packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx]: you were correct, removed

File: packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx [hunk 13]
```diff
@@ -82,34 +97,27 @@ export function BeeTableContextMenuHandler({
...
+      // See the same principle in: src/table/BeeTable/BeeTable.tsx#getColumnCount
+      const nonPlaceholderColumns = columns?.filter((col) => !col?.placeholderOf);
+      if (nonPlaceholderColumns) {
+        return nonPlaceholderColumns[columnIndex];
+      } else {
+        console.error(`No column found at [${rowIndex}, ${columnIndex}]`);
+      }
+    } else {
+      return columns?.[columnIndex];
     }
```
Comment (jomarko) [inline packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx:117]: This fixes kiegroup/kie-issues#324

**Comment by tiagobento** [comment]
@jomarko Small comment.. as I mentioned, all cells should be Copy-able, including header and rowIndex cells..

**Comment by jomarko** [comment]
@tiagobento ok, makes sense, then maybe a question, what cells can user paste value into:
- header cells - really not sure
- data cells - yes
- row index cells - no

can you help? or should I add just 'copy' as part of this PR and we can address 'paste' via different issue, if needed?

**Comment by tiagobento** [comment]
@jomarko Yes.. pasting values to header cells is going to be a little bit more complicated, as there's more than a single value, usually (E.g., Name + Data Type). Let's address "copy" here and "paste" in another ticket :)

**Review by tiagobento — APPROVED** [review]
