### PR TITLE
kie-issues#39: BPMN Editor: SuperDev mode doesn't work

### LINKED ISSUE #39: BPMN Editor: SuperDev mode doesn't work
**Step to reproduce**
- Launch BPMN Editor in SuperDev Mode
- Load any BPMN Editor with _sequence flows_
- Unmarshaller phase failed

Screenshot 2022-11-22 at 20 29 11(1)

"Error: org.kie.workbench.common.stunner.core.diagram.DiagramParsingException
    at AhO_g$.FKc_g$ [as createError_0_g$] (org.kie.workbench.common.stunner.kogito.KogitoBPMNEditor-0.js:552:10)
    at AhO_g$.QKc_g$ [as initializeBackingError_0_g$] (org.kie.workbench.common.stunner.kogito.KogitoBPMNEditor-0.js:615:44)
    at AhO_g$.wKc_g$ (org.kie.workbench.common.stunner.kogito.KogitoBPMNEditor-0.js:440:8)
    at AhO_g$.cLc_g$ (org.kie.workbench.common.stunner.kogito.KogitoBPMNEditor-0.js:714:10)
    at AhO_g$.kLc_g$ (org.kie.workbench.common.stunner.kogito.KogitoBPMNEditor-0.js:760:10)
    at new AhO_g$ (org.kie.workbench.common.stunner.kogito.KogitoBPMNEditor-0.js:786445:10)
    at YCz_g$.dDz_g$ [as lambda$1_38_g$] (org.kie.workbench.common.stunner.kogito.KogitoBPMNEditor-0.js:466388:45)
    at Function.IMH_g$ (org.kie.workbench.common.stunner.kogito.KogitoBPMNEditor-0.js:636976:32)
    at lambda_0_g$ (org.kie.workbench.common.stunner.kogito.KogitoBPMNEditor-0.js:107:27)"

### PR DESCRIPTION
**Pull request by inodeman**
Closes https://github.com/kiegroup/kie-issues/issues/39

Hi @yesamer @gitgabrio @Josephblt can you review this PR? To test the changes make sure you build kie-wb-common-stunner first as I have had issues with Hot Reload before on these changes. I have tested the changes on Linux, Windows (Thanks Wagner) and Mac OS and it works, tested it with different diagrams and also tested the issue on DMN which does not seem to have any errors. The problem seems to be an internal Runtime GWT Bug, on the issue that is present on Windows and Linux is a Javascript ClassCastException when going through the SequenceFlowImpl, on the Mac issue there seems to be an issue when processing the stream code, it is only present in Super Dev Mode and it does not happen on production build. Thanks, let me know

### CODE REVIEW

**Review by tiagobento — CHANGES_REQUESTED** [review]
@inodeman Can you please put the issue URL on the comments as well? It can be important in the future.

**Comment by tiagobento** [comment]
@inodeman It would be good to know why this happens.. is this a GWT compiler error? Runtime error? Writing the solution on the issue or on this PR's comment can be very important for future reference.

**Comment by inodeman** [comment]
> @inodeman It would be good to know why this happens.. is this a GWT compiler error? Runtime error? Writing the solution on the issue or on this PR's comment can be very important for future reference.

Hi @tiagobento added the comment of my findings about the issue

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/AssociationList.java [hunk 1]
```diff
@@ -60,6 +60,11 @@ public AssociationList() {
     }
 
     public static AssociationList fromString(String encoded) {
+        // The change below is to fix SDM issue on Mac OS
+        if (encoded != null && encoded.isEmpty()) {
+            return new AssociationList();
+        }
+
         return Optional.ofNullable(encoded)
```
Comment (gitgabrio) [inline packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/AssociationList.java]: Hi @inodeman Thanks for PR!
Would not be possible to simlpify this method and remove altogether that `Optional.ofNullable` usage ?
AFAIU, this method returns a `new AssociationList()` when

`encoded == null || encoded.isEmpty`
 Only when  `encoded.notEmpty` the "mapping" is actually invoked (side note - the filter still contains the `nonEmpty` predicate, even if checked in the newly added "if")

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/FlowElementConverter.java [hunk 2]
```diff
@@ -66,6 +67,10 @@ public Result<BpmnNode> convertNode(FlowElement flowElement) {
                                       element -> converterFactory.textAnnotationConverter().convert((TextAnnotation) element))
                 .<DataObjectReference>when(e -> e instanceof DataObjectReference,
                                            element -> converterFactory.dataObjectConverter().convert((DataObjectReference) element))
+                // The change below is to fix SDM issue for Linux/Windows
```
Comment (gitgabrio) [inline packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/FlowElementConverter.java]: Hi @inodeman 
I just checked `FlowElement` hierarchy and, actually, this `SequenceFlowImpl` is one of the direct children. 
Without this modification, how would it be possible for this method to work at all, when receiving a `SequenceFlowImpl` ? It is not even declared in the following `ignore`. 
Beside, what will happen when a children of `FlowElementImpl` is received ?
Could you please add/modify some test to verify also those conditions ?
I'm just trying to understand and never saw this `Match` class before.

**Review by gitgabrio — CHANGES_REQUESTED** [review]
Hi @inodeman Thanks for the PR! I would prefer a small modification on one of your changes

**Review by yesamer — COMMENTED** [review]
Hi @inodeman! I tested your changes, it seems the issue is still present in my local (macOS)

https://user-images.githubusercontent.com/16005046/216292679-298ed26a-d019-47ae-90f4-6795887c1472.mov

Is probably that issue related to another marshaller area? I can give you the BPMN files I'm using, just ping me :)

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/AssociationList.java (hunk 1 above)
Comment (inodeman) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/AssociationList.java]: Hi @gitgabrio I modified it

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/FlowElementConverter.java (hunk 2 above)
Comment (inodeman) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/FlowElementConverter.java]: Hi @gitgabrio removed changes from that class and modified ProcessConverterDelegate as per the code you shared

Comment (gitgabrio) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/FlowElementConverter.java]: Thanks @inodeman ! I hope everything is fixed with this PR 👍

**Comment by inodeman** [comment]
Hi @gitgabrio @yesamer @Josephblt made code changes, ready for review

**Review by Josephblt — APPROVED** [review]

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java [hunk 3]
```diff
@@ -112,17 +115,30 @@ Result<Boolean> convertEdges(BpmnNode processRoot, List<BaseElement> flowElement
...
-                .map(converterFactory.flowElementConverter()::convertNode)
-                .collect(Collectors.toList());
-
-        final Map<String, BpmnNode> resultMap = results.stream()
-                .map(Result::value)
-                .filter(Objects::nonNull)
-                .collect(Collectors.toMap(n -> n.value().getUUID(), n -> n));
-
-        return ResultComposer.composeResults(resultMap, results);
+        final List<Result<BpmnNode>> results = new ArrayList<Result<BpmnNode>>();
```
Comment (yesamer) [inline packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: @inodeman You can use the `<>` Diamond operator here

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java [hunk 4]
```diff
@@ -112,17 +115,30 @@ Result<Boolean> convertEdges(BpmnNode processRoot, List<BaseElement> flowElement
...
+        final Map<String, BpmnNode> resultMap = new HashMap<String, BpmnNode>();
```
Comment (yesamer) [inline packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: @inodeman You can use the `<>` Diamond operator here

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java [hunk 5]
```diff
@@ -112,17 +115,30 @@ Result<Boolean> convertEdges(BpmnNode processRoot, List<BaseElement> flowElement
...
+                GWT.log("Converting  " + element);
+                Result<BpmnNode> result = converterFactory.flowElementConverter().convertNode(element);
+                results.add(result);
+                GWT.log("Mapping  " + result);
+                if (result.value() != null) {
+                    BpmnNode n = result.value();
+                    resultMap.put(n.value().getUUID(), n);
+                }
+            } catch (Throwable t) {
+                GWT.log("Failed to convert/map " + element, t);
```
Comment (yesamer) [inline packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: @inodeman I would use a LOGGER here, and not the `GWT.log`.
`    private static Logger LOGGER = Logger.getLogger(ProcessConverterDelegate.class.getName());
`

**Review by yesamer — APPROVED** [review]
@inodeman It finally works! Just a couple of minor points:

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java (hunk 5 above)
Comment (gitgabrio) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: @yesamer Why "Logger" instead of "GWT.log" ? Out of curiosity....

Comment (yesamer) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: @gitgabrio `GWT.log()` works in dev mode only --> https://www.gwtproject.org/javadoc/latest/com/google/gwt/core/client/GWT.html . I would use the Logger at least in the catch body.

Comment (gitgabrio) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: @yesamer 🤔 TBH I'm not so sure. https://www.gwtproject.org/doc/latest/DevGuideLogging.html

`Most of the default Handlers are very straightforward

    SystemLogHandler - Logs to stdout. These messages can only be seen in Development Mode — look for them in the DevMode window
    DevelopmentModeLogHandler - Logs by calling method GWT.log. These messages can only be seen in Development mode — look for them in the DevMode window
    ConsoleLogHandler - Logs to the javascript console, which is used by Firebug Lite (for IE), Safari and Chrome(?)
    FirebugLogHandler - Logs to Firebug
    PopupLogHandler - Logs to the popup which appears in the upper left hand corner
    SimpleRemoteLogHandler - Discussed below, in the Remote Logging section` 

`Client vs. Server-side Logging

Although GWT emulates java.util.logging, it is important to understand the difference between server-side and client-side logging. Client-side logging logs to handlers on the client side, while server-side logging logs to handlers on the server side.

To make this clear, the client-side GWT code has a Root Logger (and logger hierarchy) that is separate from the server-side code; all of the handlers discussed above are only applicable to client-side code. If code shared by the client and server makes logging calls, then which Root Logger (and logger hierarchy) it logs to will depend on whether it is being executed on the client or server side. You should not add or manipulate Handlers in shared code, since this will not work as expected.

In [ServerLoggingArea.java](https://gwt.googlesource.com/gwt/+/master/samples/logexample/src/com/google/gwt/sample/logexample/client/ServerLoggingArea.java), you can experiment with these concepts. The buttons in that section will trigger logging calls on the server, as well as logging calls in [SharedClass.java](https://gwt.googlesource.com/gwt/+/master/samples/logexample/src/com/google/gwt/sample/logexample/shared/SharedClass.java) from both the client and server side. Note the slight differences in formatting between client-side and server-side logging, as well as the different handlers each is logged to (in the tutorial, server-side logging will simply log to stderr, while client-side logging will log to all of the Handlers discussed above).`


@inodeman Would you have the chance to give it a try ? My doubt is that "Logger" does not print on browser console (i.e. the one see inside the "Web development tools" of the browser): this is pretty important, IMO, because otherwise it is not possible to see the exception when it happen

Comment (yesamer) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: @gitgabrio 
Screenshot 2023-02-10 at 14 15 44

Comment (gitgabrio) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: @yesamer Ok, but my question is: does `Logger` print on browser console ? If not, how to print in browser console ?

Comment (inodeman) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: Hi @yesamer @gitgabrio now that i think of it, one time Roger from stunner team told me that instead of GWT.log we should use DomGlobal.console.log which logs to the console in both dev mode and production, he mentioned that since we are moving away from GWT we should use that, what do you think?

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java (hunk 3 above)
Comment (inodeman) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: Hi @yesamer will do

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java (hunk 4 above)
Comment (inodeman) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: Hi @yesamer will do

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java (hunk 5 above)
Comment (yesamer) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: @gitgabrio 
LOGGER works, it's currently used in several places in the code base. To give you an example, this is a LOGGER used to log exceptions during DMN file unmarshalling phase.
Screenshot 2023-02-10 at 18 12 57
As a result of passing an invalid DMN file, the console shows the following:
Screenshot 2023-02-10 at 18 18 31

@inodeman Good point, `DomGlobal.console.log` is a reasonable alternative. My point is just don't use `GWT.log` for the above reason, so it's fine for me to use `DomGlobal.console.log`

Comment (inodeman) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: Very well @yesamer , is it ok with you @gitgabrio ?

**Comment by gitgabrio** [comment]
@inodeman the log has to be printed always in the browser console (i.e. not
on some server file) to be readable when some issue happen: did you verify
that?

Il Ven 10 Feb 2023, 18:23 Jaime Enriquez ***@***.***> ha
scritto:

**Comment by inodeman** [comment]
Hi @gitgabrio yes, DomGlobal.console.log does what console.log (JavaScript) does, and I verified it as well, let me know

File: packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java (hunk 5 above)
Comment (gitgabrio) [reply packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/ProcessConverterDelegate.java]: Great @inodeman Fine for me! Thanks for this!

**Comment by tiagobento** [comment]
Is this good to go in? @yesamer @inodeman @Josephblt @gitgabrio

**Comment by yesamer** [comment]
> Is this good to go in? @yesamer @inodeman @Josephblt @gitgabrio

We just need to remove `GWT.log()`s and it's fine.

**Comment by inodeman** [comment]
Hi @gitgabrio @yesamer @Josephblt  changes are in to include  <> as well as removing GWT.log.

**Review by gitgabrio — APPROVED** [review]

**Review by Josephblt — APPROVED** [review]
