### PR TITLE
kie-issues#408: KIE Sandbox Quarkus Accelerators will wrongly initializate in branch different than "main"

### LINKED ISSUE #408: KIE Sandbox Quarkus Accelerators will wrongly initializate in branch different than "main"
Applying the Quarkus Accelerator in a different branch than "main" in Git repository will fail.

## Video
https://github.com/kiegroup/kie-issues/assets/24302289/42488534-9738-48a7-bd16-648e719140f5

## Steps to reproduce
- Open KIE Sandbox
- Clone a repository in a different branch than "main" (e.g. https://github.com/ljmotta/bpmn-dmn-examples)
- Apply the Quarkus Accelerator;

```[tasklist]
### Acceptance Critaria
- [ ] It should be possible to apply the Accelerators in any branch;
```

### PR DESCRIPTION
**Pull request by klbowers**
Fixes https://github.com/apache/incubator-kie-issues/issues/408, by dynamically setting the branch from workspace.descriptor as opposed to it being hardcoded as "main."

### CODE REVIEW

File: packages/online-editor/src/accelerators/AcceleratorsHooks.tsx [hunk 1]
```diff
@@ -225,7 +220,11 @@ export function useAcceleratorsDispatch(workspace: ActiveWorkspace) {
         });
 
         // Go back to main
```
Comment (tiagobento) [inline packages/online-editor/src/accelerators/AcceleratorsHooks.tsx]: Comment is outdated then 🙈

**Review by ljmotta — APPROVED** [review]

**Review by thiagoelg — APPROVED** [review]

**Review by thiagoelg — CHANGES_REQUESTED** [review]
Oops, there's probably an issue here.
Applying the accelerator with the cors-proxy service off will cause files to be moved anyway while still failing to apply the accelerator.

Edit: Nevermind

**Review by thiagoelg — APPROVED** [review]
