### PR TITLE
kie-issues#1076: Fix font color properties panel component

### LINKED ISSUE #1076: DMN Editor: Reset font button ignores font color
Node Font properties have a button for **Reset**ing to the default state. However,  this button ignores the font color.

- Create any node
- Change its font color
- Open the properties panel for the given node
- Click Font reset button - **node font color is not reset** 

This is very similar issues as #1075

### PR DESCRIPTION
**Pull request by jomarko**
In this PR we:
- closes apache/incubator-kie-issues#1076
- introduce few more playwright tests
- activate skipped playwright tests due to the apache/incubator-kie-issues#1076
- fix reset and change font color for single or multiple nodes selected

### CODE REVIEW

File: packages/dmn-editor/src/propertiesPanel/FontOptions.tsx [hunk 1]
```diff
@@ -233,7 +233,7 @@ export function FontOptions({ startExpanded, nodeIds }: { startExpanded: boolean
       setShapeStyles((shapes, state) => {
         shapes.forEach((shape) => {
           state.diagram.isEditingStyle = false;
-          shape["di:Style"]!["dmndi:FontColor"] ??= DEFAULT_FONT_COLOR;
```
Comment (jomarko) [inline packages/dmn-editor/src/propertiesPanel/FontOptions.tsx:236]: The root cause seems to be in the thing, we made a `const` object mutable. We assigned it to another variable and then started to access and assign fields of this object.

It can be seen in debug mode, if you stop `onReset` execution in moment, when invoked for a node with changed font color, you can see `DEFAULT_FONT_COLOR` is not anymore `(0,0,0)`
Screenshot 2024-04-24 164745

Comment (ljmotta) [reply packages/dmn-editor/src/propertiesPanel/FontOptions.tsx:236]: Yes, you're correct. Please fix the same way we did on the the #2254 . By spreading the `DEFAULT_FONT_COLOR` inside a object we will create a new reference. Here we keep the `??=` so it will override the previous color

File: packages/dmn-editor/src/propertiesPanel/FontOptions.tsx [hunk 2]
```diff
@@ -256,10 +256,10 @@ export function FontOptions({ startExpanded, nodeIds }: { startExpanded: boolean
...
         shape["di:Style"]!["@_fontSize"] = undefined;
         shape["di:Style"]!["@_fontFamily"] = undefined;
-        shape["di:Style"]!["dmndi:FontColor"] ??= DEFAULT_FONT_COLOR;
-        shape["di:Style"]!["dmndi:FontColor"]["@_red"] = DEFAULT_FONT_COLOR["@_red"];
-        shape["di:Style"]!["dmndi:FontColor"]["@_green"] = DEFAULT_FONT_COLOR["@_green"];
-        shape["di:Style"]!["dmndi:FontColor"]["@_blue"] = DEFAULT_FONT_COLOR["@_blue"];
+        shape["di:Style"]!["dmndi:FontColor"] ??= { "@_red": 0, "@_green": 0, "@_blue": 0 };
+        shape["di:Style"]!["dmndi:FontColor"]!["@_red"] = DEFAULT_FONT_COLOR["@_red"];
+        shape["di:Style"]!["dmndi:FontColor"]!["@_green"] = DEFAULT_FONT_COLOR["@_green"];
+        shape["di:Style"]!["dmndi:FontColor"]!["@_blue"] = DEFAULT_FONT_COLOR["@_blue"];
```
Comment (ljmotta) [inline packages/dmn-editor/src/propertiesPanel/FontOptions.tsx]: By spreading the `DEFAULT_FONT_COLOR` inside a new object, we will not need the lines 260, 261 and 262. It's important to use the `=` instead of `??=` too.

File: packages/dmn-editor/src/propertiesPanel/ShapeOptions.tsx
Comment (ljmotta) [inline packages/dmn-editor/src/propertiesPanel/ShapeOptions.tsx:1]: While solving the conflicts, please use the #2254 changes

**Review by ljmotta — COMMENTED** [review]
Thanks @jomarko . You got a few errors! I've just made some comments inline.

**Review by ljmotta — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]
