### PR TITLE
kie-issues#2183: DMN Editor: Does not autocomplete decision name when required decision uses namespace in href

### LINKED ISSUE #2183: DMN Editor: Does not autocomplete decision name when required decision uses namespace in href
In DMN models, when a required decision is referenced using a full namespace in the href attribute, the expression editor fails to offer autocompletion for that decision.

For example, using:
eg. `<requiredDecision href="http://www.example.org/Definitions01.xml#prebureauriskDec01"/>`
will prevent `prebureauriskDec01` from appearing in autocompletion suggestions.
However, if the same decision is referenced without a namespace:
eg. `<requiredDecision href="#prebureauriskDec01"/>`
then autocompletion works correctly.

This issue only affects references within the same DMN model.

When users include a namespace in the href to reference a decision inside the same file, the editor does not recognize it for autocompletion.

### PR DESCRIPTION
**Pull request by danielzhe**
Closes: https://github.com/apache/incubator-kie-issues/issues/2183

https://github.com/user-attachments/assets/3fe2041f-884d-416d-abbf-1b22244c6dbb

### CODE REVIEW

File: packages/dmn-feel-antlr4-parser/src/parser/IdentifiersRepository.ts [hunk 1]
```diff
@@ -825,9 +827,13 @@ export class IdentifiersRepository {
 
   private addInputVariable(parent: IdentifierContext, requirement: DmnInformationRequirement) {
     if (requirement.requiredDecision) {
-      parent.inputIdentifiers.push(requirement.requiredDecision["@_href"]?.replace("#", ""));
+      parent.inputIdentifiers.push(
+        requirement.requiredDecision["@_href"]?.replace(this._localNamespace, "").replace("#", "")
```
Comment (danielzhe) [inline packages/dmn-feel-antlr4-parser/src/parser/IdentifiersRepository.ts:831]: We don't care about local namespace, that's why we remove if it is present.
For included models, the code that adds the variables is another, so that's why we can safely remove the namespace: if we are here, it is a local node for sure.

**Review by jomarko — COMMENTED** [review]
Hi @danielzhe . Thank you for the PR. Especially for the tests included in the PR.

However, I struggle to confirm fix in `online-editor` module. Coudl you please check if I build and start it properly?
- `pnpm bootstrap -F @kie-tools/online-editor... -F '!@kie-tools/stunner-editors...'`
- `pnpm -F @kie-tools/online-editor... -F '!@kie-tools/stunner-editors...'  build:dev`
- `pnpm -F @kie-tools/online-editor start`

See the attached screenshot where no autocompletion appears.

image

**Comment by thiagoelg** [comment]
@jomarko When you do `-F '!@kie-tools/stunner-editors...'` you are not only excluding the `@kie-tools/stunner-editors` package, but all of its dependencies as well.

The correct commands should be:
```
pnpm bootstrap -F @kie-tools/online-editor... -F '!@kie-tools/stunner-editors'
pnpm -F @kie-tools/online-editor... -F '!@kie-tools/stunner-editors'  build:dev
pnpm -F @kie-tools/online-editor start
```

But in this case, it shouldn't cause any trouble for your tests, since the `stunner-editors` package doesn't share many dependencies with other packages.

---

@danielzhe Can you check Jozef's review?

**Comment by danielzhe** [comment]
@jomarko I tested in Online Editor and it is working. I think you have to build everything. I builded with `pnpm -F online-editor... build:dev`

**Comment by danielzhe** [comment]
[required-decision-with-namespace-in-href.txt](https://github.com/user-attachments/files/24723608/required-decision-with-namespace-in-href.txt)

File for test

**Review by jomarko — APPROVED** [review]
@danielzhe . Thank you Daniel. I have rechecked the PR once I built all without any exclude. I can confirm it works. 

During previous check it was probably my fault of building PR not properly.

**Review by thiagoelg — APPROVED** [review]
