### PR TITLE
kie-issues#455: Refactor the Boxed Expression Editor to not have its own model, and instead use the DMN Marshaller's types

### LINKED ISSUE #401: DMN Editor's Boxed Expression Editor: cut/paste functionality must generate new IDs
In the DMN editor, functionality is present to duplicate rows and to cut and paste (multiple) cells. In these cases, all newly created cells must become an id of their own. Currently, the id is being copied, which obviously is a bug. Note that when a cell is being copied that contains a decision table or context, there can be cells contained in there too. These cells must become an id of their own as well.

Today I have been editing a context, using cut/paste of decision tables inside the context. When compiling, I got the following error message:

~~~
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.252 s
[INFO] Finished at: 2023-08-07T11:12:41+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.kie.kogito:kogito-maven-plugin:1.36.0.Final:generateModel (default-generateModel) on project rvp-machine: Execution default-generateModel of goal org.kie.kogito:kogito-maven-plugin:1.36.0.Final:generateModel failed: DMN Validation schema and model validation contained errors
[ERROR] You may configure kogito.decisions.validation=IGNORE to ignore validation errors
[ERROR] DMN Validation errors:
[ERROR] : Failed XML validation of DMN file: cvc-id.2: There are multiple occurrences of ID value '_EC229F1E-A277-4B95-8B36-622536A10A73'.,
[ERROR] : One of the supplied DMN Models has failed validation; cannot proceed to validation of the remaining DMN Models.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
~~~

And here is the result after my editing:
[pvc_PlannenVaccinatieComponent.zip](https://github.com/kiegroup/kie-issues/files/12274499/pvc_PlannenVaccinatieComponent.zip)

### LINKED ISSUE #455: Refactor the Boxed Expression Editor to not have its own model, and instead use the DMN Marshaller's types
After #220, there are TypeScript types available to represent DMN files, including Expressions. The Boxed Expression Editor currently has its own types defined, since it was created prior to the React-based DMN Marshaller and DMN Editor. We should be able to remove the `beeToDmn` and `dmnToBee` methods from the React-based DMN Editor after this task is complete.

### LINKED ISSUE #536: On nested Decision tables the input and output columns are not set by the parent expression
Currently, nested Decision tables doesn't correctly create the inputs and outputs columns. e.g. on a Boxed Context with a Decision table as a result should load all context entries as input and its output should be the decision name.

## Video
The following video shows what is happening and is the expected behavior:
https://github.com/kiegroup/kie-issues/assets/24302289/0cb120c1-8f35-4f83-a6f2-b13eaa0ad46d

### PR DESCRIPTION
**Pull request by danielzhe**
Closes: https://github.com/apache/incubator-kie-issues/issues/455
Closes: https://github.com/apache/incubator-kie-issues/issues/536
Closes: https://github.com/apache/incubator-kie-issues/issues/401

This PR removes the Boxed Expression Editor's types to use the DMN Marshaller types, so we don't have any more to deal with conversions between BEE and the Marshaller, making it easier to maintain, faster add new features since we don't have to deal with that kind of conversion and faster to the end user since there is no more a conversion to be made every time the BEE is opened.

### CODE REVIEW

File: packages/unitables-dmn/src/DmnRunnerOutputsTable.tsx [hunk 1]
```diff
@@ -399,8 +399,11 @@ function OutputsBeeTable({ id, i18n, outputsPropertiesMap, results, scrollablePa
     return [BeeTableOperation.SelectionCopy];
   }, []);
 
+  const widthsById = useMemo(() => new Map(), []); // FIXME: Tiago
```
Comment (tiagobento) [inline packages/unitables-dmn/src/DmnRunnerOutputsTable.tsx]: 🙈

File: packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.java [hunk 2]
```diff
@@ -649,7 +649,7 @@ private String getTypeRef() {
         return qName.getLocalPart();
     }
 
-    private PMMLParam[] buildPmmlParams() {
+    private PMMLParam[] buildpmmlDocuments() {
```
Comment (tiagobento) [inline packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.java]: Little typo..

File: packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionPropsFiller.java [hunk 3]
```diff
@@ -105,7 +105,7 @@ public static ExpressionProps buildAndFillJsInteropProp(final Expression wrapped
                                           outputConvertForDecisionTableProps(decisionTableExpression, expressionName, dataType),
                                           rulesConvertForDecisionTableProps(decisionTableExpression));
         }
-        return new ExpressionProps(expressionId, expressionName, dataType, UNDEFINED.getText());
+        return null;
```
Comment (tiagobento) [inline packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionPropsFiller.java]: Doesn't this have bad implications? I mean, `gwtToDmn` and `dmnToGwt` should be able to handle it, no?

File: packages/stunner-editors-dmn-loader/src/beeToGwt.ts
Comment (tiagobento) [inline packages/stunner-editors-dmn-loader/src/beeToGwt.ts:1]: I think this would be `dmnToGwt`.

File: packages/stunner-editors-dmn-loader/src/gwtToBee.ts
Comment (tiagobento) [inline packages/stunner-editors-dmn-loader/src/gwtToBee.ts:1]: And this would be `gwtToDmn`

File: packages/stunner-editors-dmn-loader/src/index.tsx [hunk 4]
```diff
@@ -132,38 +143,42 @@ const BoxedExpressionEditorWrapper: React.FunctionComponent<BoxedExpressionEdito
     };
   }, [boxedExpressionEditorRootNode]);
 
+  const onWidthsChange = useCallback(() => {}, []);
```
Comment (tiagobento) [inline packages/stunner-editors-dmn-loader/src/index.tsx]: 🙈?

File: packages/unitables/src/bee/UnitablesBeeTable.tsx [hunk 5]
```diff
@@ -303,8 +303,11 @@ export function UnitablesBeeTable({
     return row.original.id;
   }, []);
 
+  const widthsById = useMemo(() => new Map(), []); // FIXME: Tiago
```
Comment (tiagobento) [inline packages/unitables/src/bee/UnitablesBeeTable.tsx]: 🙈?

File: packages/stunner-editors-dmn-loader/src/Dmn15Spec.ts
Comment (tiagobento) [inline packages/stunner-editors-dmn-loader/src/Dmn15Spec.ts:1]: Not sure why we need this file here...

File: packages/stunner-editors-dmn-loader/package.json [hunk 6]
```diff
@@ -16,6 +16,7 @@
     "@kie-tools-core/monaco-editor": "workspace:*",
     "@kie-tools/boxed-expression-component": "workspace:*",
     "@kie-tools/dmn-feel-antlr4-parser": "workspace:*",
+    "@kie-tools/dmn-marshaller": "workspace:*",
```
Comment (tiagobento) [inline packages/stunner-editors-dmn-loader/package.json:19]: 👍

File: packages/scesim-editor/src/table/TestScenarioTable.tsx [hunk 7]
```diff
@@ -1121,6 +1121,7 @@ function TestScenarioTable({
         shouldRenderRowIndexColumn={!isBackground}
         shouldShowColumnsInlineControls={true}
         shouldShowRowsInlineControls={!isBackground}
+        widthsById={new Map<string, number[]>()} // The widths in SceSim are handled direct in the columns
```
Comment (tiagobento) [inline packages/scesim-editor/src/table/TestScenarioTable.tsx]: Can we create a constant here in the global scope? There's really no need for this new Map to be created every time this component re-renders.

File: packages/dmn-editor/src/boxedExpressions/getDefaultExpressionDefinitionByLogicType.tsx [hunk 8]
```diff
@@ -48,189 +46,189 @@ import {
 import {
   INVOCATION_EXPRESSION_DEFAULT_PARAMETER_NAME,
   INVOCATION_EXPRESSION_DEFAULT_PARAMETER_DATA_TYPE,
-  INVOCATION_EXPRESSION_DEFAULT_PARAMETER_LOGIC_TYPE,
 } from "@kie-tools/boxed-expression-component/dist/expressions/InvocationExpression";
 import { RELATION_EXPRESSION_DEFAULT_VALUE } from "@kie-tools/boxed-expression-component/dist/expressions/RelationExpression";
 import { DataTypeIndex } from "../dataTypes/DataTypes";
 import { isStruct } from "../dataTypes/DataTypeSpec";
+import { DMN15__tContextEntry } from "@kie-tools/dmn-marshaller/src/schemas/dmn-1_5/ts-gen/types";
```
Comment (tiagobento) [inline packages/dmn-editor/src/boxedExpressions/getDefaultExpressionDefinitionByLogicType.tsx]: Oh oh... We're not supposed to import from `src` dirs.

**Review by tiagobento — CHANGES_REQUESTED** [review]
Didn't look at the `boxed-expression-component` package yet, though.

File: packages/dmn-editor/src/boxedExpressions/getDefaultExpressionDefinitionByLogicType.tsx (hunk 8 above)
Comment (tiagobento) [reply packages/dmn-editor/src/boxedExpressions/getDefaultExpressionDefinitionByLogicType.tsx]: Please check other places as well.. I think we have a Linter rule for this... no?

File: packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionPropsFiller.java (hunk 3 above)
Comment (danielzhe) [reply packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionPropsFiller.java]: We don't have the undefined expression anymore.

File: packages/stunner-editors-dmn-loader/src/gwtToBee.ts
Comment (danielzhe) [reply packages/stunner-editors-dmn-loader/src/gwtToBee.ts:1]: But it is still DMN in GWT, so, in my opinion, it doesn't make sense `gwtToDmn` because we're converting "dmn gwt to real dmn (bee)".

File: packages/stunner-editors-dmn-loader/src/index.tsx (hunk 4 above)
Comment (danielzhe) [reply packages/stunner-editors-dmn-loader/src/index.tsx]: My question is: do we need it? I think we may not need this `onWidthsChange` anymore, at least I didn't find any scenario where it is required with this refactor. Should we remove it or you know any scenario where this is required?

File: packages/stunner-editors-dmn-loader/src/Dmn15Spec.ts
Comment (danielzhe) [reply packages/stunner-editors-dmn-loader/src/Dmn15Spec.ts:1]: It is required for the conversions Bee->GWT / GWT->Bee

Here, for example:
https://github.com/apache/incubator-kie-tools/pull/2202/files#diff-c9884920927c2c2570b5d71274cbcff7d352e290f2629a03acc9375a17d57caeR198

I didn't noticed that  have this file in `dmn-editor`

File: packages/scesim-editor/src/table/TestScenarioTable.tsx (hunk 7 above)
Comment (danielzhe) [reply packages/scesim-editor/src/table/TestScenarioTable.tsx]: Removed. It is optional now.

File: packages/dmn-editor/src/boxedExpressions/getDefaultExpressionDefinitionByLogicType.tsx (hunk 8 above)
Comment (danielzhe) [reply packages/dmn-editor/src/boxedExpressions/getDefaultExpressionDefinitionByLogicType.tsx]: I didn't do it on purpose. I trusted the alt+enter of the IDE and got trolled.  xD

File: packages/boxed-expression-component/src/expressions/BoxedExpressionEditor/BoxedExpressionEditorContext.tsx [hunk 9]
```diff
@@ -64,24 +67,32 @@ export function useBoxedExpressionEditorDispatch() {
...
 
   const editorRef = useRef<HTMLDivElement>(null);
 
-  const dispatch = useMemo(
+  const dispatch = useMemo<BoxedExpressionEditorDispatchContextType>(
     () => ({
-      setExpression: setExpressionDefinition,
+      setExpression: onExpressionChange,
+      setWidth: ({ id, values }) => {
+        console.log("width" + id);
```
Comment (ljmotta) [inline packages/boxed-expression-component/src/expressions/BoxedExpressionEditor/BoxedExpressionEditorContext.tsx]: I guess we could change this to a debug console?

File: packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx [hunk 10]
```diff
@@ -296,63 +407,92 @@ export function DecisionTableExpression(
...
       }),
-    [beeTableColumns, decisionTableExpression.rules]
+    [beeTableColumns, decisionTableExpression.output.length, decisionTableExpression.rule]
   );
 
   const onCellUpdates = useCallback(
     (cellUpdates: BeeTableCellUpdate<ROWTYPE>[]) => {
       setExpression((prev: DecisionTableExpressionDefinition) => {
-        const n = { ...prev };
+        let n = { ...prev };
```
Comment (ljmotta) [inline packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx]: A better name here? newExpression/prevExpression, WDYT?

File: packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx [hunk 11]
```diff
@@ -296,63 +407,92 @@ export function DecisionTableExpression(
...
 
         cellUpdates.forEach((u) => {
```
Comment (ljmotta) [inline packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx]: The same for `u`.

File: packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx [hunk 12]
```diff
@@ -365,47 +505,59 @@ export function DecisionTableExpression(
     (columnUpdates: BeeTableColumnUpdate<ROWTYPE>[]) => {
       setExpression((prev: DecisionTableExpressionDefinition) => {
         const n = { ...prev };
-        for (const u of columnUpdates) {
+        for (const columnUpdate of columnUpdates) {
```
Comment (ljmotta) [inline packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx:495]: 👍 👍 👍  😄

File: packages/boxed-expression-component/src/expressions/ExpressionDefinitionRoot/ExpressionContainer.tsx [hunk 13]
```diff
@@ -71,12 +74,12 @@ export const ExpressionContainer: React.FunctionComponent<ExpressionContainerPro
...
     (contextExpressionDefinition: ContextExpressionDefinition) => {
-      const contextEntries = contextExpressionDefinition.contextEntries;
+      const contextEntries = contextExpressionDefinition.contextEntry ?? [];
       for (const contextEntry of contextEntries) {
         variables?.repository.addVariableToContext(
-          contextEntry.entryInfo.id,
-          contextEntry.entryInfo.name,
-          contextExpressionDefinition.id
+          contextEntry["@_id"]!,
+          contextEntry["@_label"] ?? "<var>",
```
Comment (ljmotta) [inline packages/boxed-expression-component/src/expressions/ExpressionDefinitionRoot/ExpressionContainer.tsx]: Could you add a comment for the `"<var>"`?

File: packages/boxed-expression-component/src/expressions/FunctionExpression/FeelFunctionExpression.tsx [hunk 14]
```diff
@@ -211,16 +210,17 @@ export function FeelFunctionImplementationCell({
   rowIndex,
   columnIndex,
   parentElementId,
+  widthsById,
 }: BeeTableCellProps<FEEL_ROWTYPE> & { parentElementId: string }) {
-  const functionExpression = data[rowIndex].functionExpression as FeelFunctionExpressionDefinition;
+  const functionExpression = data[rowIndex].functionExpression; // as FeelFunctionExpressionDefinition;
```
Comment (ljmotta) [inline packages/boxed-expression-component/src/expressions/FunctionExpression/FeelFunctionExpression.tsx]: Left over?

File: packages/stunner-editors-dmn-loader/src/DmnBuiltInDataType.ts
Comment (ljmotta) [inline packages/stunner-editors-dmn-loader/src/DmnBuiltInDataType.ts:1]: Should we not use the `boxed-expression-component` one? Or it's necessary to duplicate it?

**Review by ljmotta — COMMENTED** [review]
Just minor catches, I saw a few single char variables, which on small scopes are ok, but some of them on the middle of a big logic can be a little difficult to follow.

File: packages/boxed-expression-component/src/expressions/ExpressionDefinitionRoot/ExpressionContainer.tsx (hunk 13 above)
Comment (danielzhe) [reply packages/boxed-expression-component/src/expressions/ExpressionDefinitionRoot/ExpressionContainer.tsx]: It can be anything. I'll just change to empty instead.

File: packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionPropsFiller.java (hunk 3 above)
Comment (tiagobento) [reply packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionPropsFiller.java]: @danielzhe But we didn't change GWT's implementation, nor the original ExpressionDefinition interface, right? My point is that converting an Undefined expression to `null` or `undefined` would be the job for the `mapping.ts` functions....

File: packages/stunner-editors-dmn-loader/src/gwtToBee.ts
Comment (tiagobento) [reply packages/stunner-editors-dmn-loader/src/gwtToBee.ts:1]: Ok, I guess it's fine :P

File: packages/stunner-editors-dmn-loader/src/index.tsx (hunk 4 above)
Comment (tiagobento) [reply packages/stunner-editors-dmn-loader/src/index.tsx]: If we don't have this callback set, the widths cannot be persisted be the containing app/component, no? I mean, how do they know that widths changed inside BoxedExpressionComponent?

**Comment by tiagobento** [comment]
Build is green but there's an issue we found with Boxed Lists containing undefined expressions. @ljmotta is investigating.

**Review by tiagobento — APPROVED** [review]

**Review by ljmotta — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]

**Review by ljmotta — APPROVED** [review]
