### PR TITLE
kie-issues#1734: KIE Tools: TypeError when invoking Java method inside BKM

### LINKED ISSUE #1734: TypeError when invoking Java method inside BKM
**Description:**
I encountered a TypeError while attempting to invoke a Java method inside a Business Knowledge Model (BKM) in the DMN editor. The error occurs consistently and prevents the proper execution of the intended functionality.

**Steps to Reproduce:**
1. Open the DMN editor at [sandbox.kie.org](https://sandbox.kie.org/).
2. Create or open a DMN model.
3. Add a Business Knowledge Model (BKM) to the canvas.
4. Attempt to invoke a Java method inside the BKM.
5. Observe the error.

**Expected Behavior:**
The Java method should be invoked successfully within the BKM, and the corresponding behavior should execute as expected.

**Actual Behavior:**
The following error occurs, halting the operation:

{
  "name": "TypeError",
  "message": "Cannot assign to read only property 'expression' of object '#<Object>'",
  "stack": "TypeError: Cannot assign to read only property 'expression' of object '#<Object>'
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4919143
    at getNewExpression (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4772205)
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4878098
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:5125756
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4761941
    at Object.produce (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4762093)
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4761925
    at i (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4620915)
    at n.setState (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:5543209)
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:5125703
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4878019
    at setExpression (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4772146)
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4919111
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4854570
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4829227
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4829276
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:6080711
    at Pl (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4391159)
    at t.unstable_runWithPriority (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4548539)
    at Go (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4331794)
    at Il (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4390622)
    at Be (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4402863)
    at Qt (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4310559)"
}

**Environment:**
Product: https://sandbox.kie.org/#/
Product Version: 10.0.0
Browser: Chrome 131.0.6778
Operating System: Windows 11

**Video to Reproduce:**
Bug

### PR DESCRIPTION
**Pull request by Kusuma04-dev**
closes https://github.com/apache/incubator-kie-issues/issues/1734 TypeError when invoking Java method inside BKM

### CODE REVIEW

**Review by jomarko — APPROVED** [review]
I can confirm now the java function class and method signature can be edited as in BKM node so in Decision Node - Context Entry - Function

**Review by klbowers — APPROVED** [review]

File: packages/boxed-expression-component/src/expressions/FunctionExpression/JavaFunctionExpression.tsx [hunk 1]
```diff
@@ -346,7 +346,13 @@ export function JavaFunctionExpression({
               expression: {
                 __$$element: "context",
                 ...context,
-                contextEntry: [clazz, method],
+                contextEntry: [
+                  {
+                    ...clazz,
+                    expression: newExpression,
```
Comment (ljmotta) [inline packages/boxed-expression-component/src/expressions/FunctionExpression/JavaFunctionExpression.tsx]: As we don't re-use the variable, could you inline it here?

File: packages/boxed-expression-component/src/expressions/FunctionExpression/JavaFunctionExpression.tsx [hunk 2]
```diff
@@ -371,7 +377,13 @@ export function JavaFunctionExpression({
               expression: {
                 __$$element: "context",
                 ...context,
-                contextEntry: [clazz, method],
+                contextEntry: [
+                  clazz,
+                  {
+                    ...method,
+                    expression: newExpression,
```
Comment (ljmotta) [inline packages/boxed-expression-component/src/expressions/FunctionExpression/JavaFunctionExpression.tsx]: Same.

**Review by ljmotta — CHANGES_REQUESTED** [review]
@Kusuma04-dev Thanks for the PR, I've made some comments inline.

File: packages/boxed-expression-component/src/expressions/FunctionExpression/JavaFunctionExpression.tsx (hunk 1 above)
Comment (Kusuma04-dev) [reply packages/boxed-expression-component/src/expressions/FunctionExpression/JavaFunctionExpression.tsx]: Hi , Done.

File: packages/boxed-expression-component/src/expressions/FunctionExpression/JavaFunctionExpression.tsx (hunk 2 above)
Comment (Kusuma04-dev) [reply packages/boxed-expression-component/src/expressions/FunctionExpression/JavaFunctionExpression.tsx]: Done

**Review by danielzhe — APPROVED** [review]
Great work!

**Review by ljmotta — APPROVED** [review]
@Kusuma04-dev LGTM!
