### PR TITLE
kie-issues#1514: Test Scenario Editor:  Advanced use cases (Expressions, List)

### LINKED ISSUE #1514: Test Scenario Editor: Extending Data Object Dock with Advanced use cases (eg. Expressions)
Use case to be analyzed improved:

- [x] Expression
- [x] Collections
- [x] Nested Data Objects (https://github.com/apache/incubator-kie-issues/issues/1810)
- [x] Disable the creation of new RULE-based test scenarios

### LINKED ISSUE #1810: New Test Scenario Editor for DMN with nested structures
This issue belongs to the epic https://github.com/apache/incubator-kie-issues/issues/453. Without this issue, the New SceSim editor can not be assumed as matured and Classic SceSim editor needs to be kept.

### Steps to reproduce
1. Please open `dmn-quarkus-example` project, use main branch (https://github.com/apache/incubator-kie-kogito-examples/tree/main/kogito-quarkus-examples/dmn-quarkus-example)
2. add `a.dmn` [1] into `src/main/resources` 
3. create new scesim file and try to set is as DMN scesim file for the `a.dmn`
4. keep the `autofill` checked
5. once created, go through the given column headers, notice nothing is selected `DMN Nodes selector` panel [2]
6. it seems also impossible to assign `GIVEN` column to a nested structure like `Person.Address.State.Continent`

[1] 

[a.dmn.txt](https://github.com/user-attachments/files/18703165/a.dmn.txt)

[2]

Image

### PR DESCRIPTION
**Pull request by yesamer**
Closes: https://github.com/apache/incubator-kie-issues/issues/1514
Closes: https://github.com/apache/incubator-kie-issues/issues/1810

In this PR:

- An alert element is shown when trying to create a new RULE-based Test Scenario. 
Screenshot 2025-02-21 at 17 19 59

- Expressions column types are now supported
Screenshot 2025-02-21 at 17 25 21

- List types are now supported. Please notice the Collection Editor present in the GWT-Editor is still not implemented, this will be managed in a future ticket
Screenshot 2025-02-21 at 17 25 53

- Selection of nested element fixed (https://github.com/apache/incubator-kie-issues/issues/1810)

https://github.com/user-attachments/assets/d80199e3-8817-4fc8-9524-e26696b20b37

### CODE REVIEW

**Comment by jomarko** [comment]
Please resolve conflicts

**Review by jomarko — COMMENTED** [review]
`Expressions column types are now supported` really not sure how to construct such column, is this documented somewhere please?

`Collections` is it expected I see `java.util.List` for a data type that is completely defined just in DMN?
image

`Nested` is this expected? notice `New property` in the right panel, but no mention in table column
image

**Comment by yesamer** [comment]
@jomarko This is how to create an expression 

https://github.com/user-attachments/assets/12a05a7e-b2bd-4060-9afc-dfba6ac9565f

Can you please share with me the DMN files you're using for the Collection and Nested case, please?

**Comment by yesamer** [comment]
@jomarko mmh... An example similar to yours behaves differently in my local 
Screenshot 2025-02-25 at 14 19 21
Can you please share the DMN files?

File: packages/scesim-editor/src/store/TestScenarioEditorStore.ts [hunk 1]
```diff
@@ -50,10 +50,13 @@ export type TestScenarioAlert = {
...
-  id: string;
+  id: string; // UI-Scope only
   children?: TestScenarioDataObject[];
-  customBadgeContent?: string;
-  isSimpleTypeFact?: boolean;
+  className?: string;
+  collectionGenericType?: string[];
+  customBadgeContent?: string; // UI-Scoped only
+  expressionElements: string[];
+  hasBadge?: boolean; // UI-Scoped only
```
Comment (tiagobento) [inline packages/scesim-editor/src/store/TestScenarioEditorStore.ts]: Can you please explain what "UI-Scoped only" means?

File: packages/scesim-editor/tests-e2e/scesimEditor/backgroundTable/populate.spec.ts [hunk 2]
```diff
@@ -70,6 +70,7 @@ test.describe("Populate decision background table", () => {
 });
 
 test.describe("Populate rule background table", () => {
+  test.skip(true, "Rule-Based Test Scenario is not enabled");
```
Comment (tiagobento) [inline packages/scesim-editor/tests-e2e/scesimEditor/backgroundTable/populate.spec.ts]: May I ask you to please file an issue at `kie-issues` and link this skipped test to it via an annotation? @ljmotta Would you be available please to tell @yesamer what's the best way to do this for Playwright tests? Thank you!

File: packages/scesim-editor/tests-e2e/scesimEditor/testScenarioTable/populate.spec.ts [hunk 3]
```diff
@@ -104,6 +104,7 @@ test.describe("Populate decision test scenario table", () => {
 });
 
 test.describe("Populate rule test scenario table", () => {
+  test.skip(true, "Rule-Based Test Scenario is not enabled");
```
Comment (tiagobento) [inline packages/scesim-editor/tests-e2e/scesimEditor/testScenarioTable/populate.spec.ts]: Same.

File: packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx [hunk 4]
```diff
@@ -288,23 +300,20 @@ function TestScenarioDataSelectorPanel() {
...
         .join(".");
     }
 
-    //TODO 1 This not work with multiple level and expressions fields. see kie-issues#1514
-    const treeViewItemToActivate = filteredDataObjects
-      .reduce((acc: TestScenarioDataObject[], item) => {
-        return item.children ? acc.concat(item.children) : acc;
-      }, [])
-      .filter((item) => item.id === fieldID);
+    const treeViewItemToActivate = findTestScenarioDataObjectById(filteredDataObjects, fieldID)!;
```
Comment (tiagobento) [inline packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx]: Not memoized. Please wrap it in a `useMemo` with the matching array of dependencies.

File: packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx [hunk 5]
```diff
@@ -202,6 +202,18 @@ function TestScenarioDataSelectorPanel() {
...
+  const findTestScenarioDataObjectById = useCallback(
+    (dataObjects: TestScenarioDataObject[], id: string): TestScenarioDataObject => {
+      let dataObjectToReturn = dataObjects.find((dataObject) => id.startsWith(dataObject.id));
+      if (dataObjectToReturn?.id !== id && dataObjectToReturn?.children) {
+        dataObjectToReturn = findTestScenarioDataObjectById(dataObjectToReturn.children, id);
+      }
+      return dataObjectToReturn!;
+    },
+    []
+  );
```
Comment (tiagobento) [inline packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx]: This function can live in the global scope, outside of the function component.

File: packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx [hunk 6]
```diff
@@ -288,23 +300,20 @@ function TestScenarioDataSelectorPanel() {
     if (isExpressionType) {
       fieldID = selectedColumnMetadata.factMapping.expressionElements!.ExpressionElement![0].step.__$$text;
     } else if (isSimpleTypeFact) {
-      fieldID = selectedColumnMetadata.factMapping.expressionElements!.ExpressionElement![0].step.__$$text.concat(".");
+      fieldID = selectedColumnMetadata.factMapping
```
Comment (tiagobento) [inline packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx]:
```suggestion
      fieldId = selectedColumnMetadata.factMapping
```

File: packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx (hunk 5 above)
Comment (tiagobento) [reply packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx]: It seems you have other `useCallback`s that can be moved out of the component too.

**Review by tiagobento — CHANGES_REQUESTED** [review]
Thank you @yesamer! Left some comments inline.

File: packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx (hunk 6 above)
Comment (yesamer) [reply packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx]: Done

File: packages/scesim-editor/src/store/TestScenarioEditorStore.ts (hunk 1 above)
Comment (yesamer) [reply packages/scesim-editor/src/store/TestScenarioEditorStore.ts]: Removed - It was a personal note to remember which fields are used for the TreeViewItem component

File: packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx (hunk 4 above)
Comment (yesamer) [reply packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx]: Mmhh, are you sure? that is inside a `useEffect()` block of code. 
If I try it, it leads to this error:
`React Hook "useMemo" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function.`

File: packages/scesim-editor/tests-e2e/scesimEditor/backgroundTable/populate.spec.ts (hunk 2 above)
Comment (yesamer) [reply packages/scesim-editor/tests-e2e/scesimEditor/backgroundTable/populate.spec.ts]: Done

File: packages/scesim-editor/tests-e2e/scesimEditor/testScenarioTable/populate.spec.ts (hunk 3 above)
Comment (yesamer) [reply packages/scesim-editor/tests-e2e/scesimEditor/testScenarioTable/populate.spec.ts]: Done

File: packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx (hunk 5 above)
Comment (yesamer) [reply packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx]: Done

File: packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx (hunk 4 above)
Comment (tiagobento) [reply packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx]: Oops, my bad. Didn't see this was inside a useEffect.

**Review by tiagobento — APPROVED** [review]

**Comment by yesamer** [comment]
@tiagobento Do you think we can merge this?

**Comment by tiagobento** [comment]
I'd like more people to look into it, if that's okay. I'm happy to merge it if you need it merged today, though. Let me know.

**Comment by yesamer** [comment]
@tiagobento If we have time, I'm fine with that.

**Review by thiagoelg — APPROVED** [review]

File: packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx [hunk 7]
```diff
@@ -52,6 +53,105 @@ const enum TestScenarioDataSelectorState {
   TREEVIEW_ENABLED_ONLY, // TreeView component is enabled only, in a read only mode (when a column is selected)
 }
 
+/* It checks if the given root Data Object is already assigned */
+const isRootDataObjectAssignable = (
+  dataObject: TestScenarioDataObject,
+  assignedExpressionElements: SceSim__expressionElementsType[]
+) => {
+  //TODO change this
```
Comment (thiagoelg) [inline packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx]: Is this a leftover? If not it would be cool to know what needs to be done later.

Comment (yesamer) [reply packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx]: @thiagoelg It's a leftover, removed. Thank you.
