### PR TITLE
kie-issues#87: Refactor the React-based Boxed Expression Component to be able to delete the GWT-based one

### LINKED ISSUE #87: Refactor the React-based Boxed Expression Component to be able to delete the GWT-based one
The new, React-based Boxed Expression Editor needed some refactoring before we could aim for deleting the old, GWT-based Boxed Expression Editor.

---

Live prototype: https://tiagobento.github.io/prototypes/bee/
_(Last update: 2023-Apr-12, SHA: a6e3461e730fc2eee85f714843522fb9ed6903f0)_

Working branch: https://github.com/tiagobento/kie-tools/tree/bee-reisizing-perf

---

This refactor has the goal of making it easier to evolve the component, making room for new features.
Things to improve on this refactoring:

- State management
- Selection mechanism
- Resizing mechanism
- Context menu mechanism
- Performance improvements
- Integration with the DMN Editor
- Integration with the DMN Runner

## WRAP-UP

- [x] Make sure that we have green builds on https://github.com/tiagobento/kie-tools/pull/83
- [x] Fix `CI :: Code formatting / check`.
- [x] Merge `kiegroup/kie-tools#main` branch with `tiagobento/kie-tools#bee-reisizing-perf`.
- [x] Fix VS Code IT -> `KIE Editors Integration Test Suite - DMN Editor`
- [x] Console error:
  > Failed to decode downloaded font: http://localhost:3015/6f75249988833dd9f4297c9781ad35ff.ttf
      localhost/:1 OTS parsing error: invalid sfntVersion: 1702391919
- [x] Make sure keyboard shortcuts / navigation works well on Windows and Linux too.
- [x] CSS differences on the DMN Editor compared to the showcase app on `boxed-expression-component`.
- [x] [DMN Editor] React-based Boxed Expression Component Management
- - [x] Set the React-based Boxed Expression Component as the default choice
- - [x] Related to the above point, standalone now needs this fix --> https://github.com/kiegroup/kie-issues/issues/84
- - [x] Improved link back to DRG;
- - [x] Improved GWT and React layers API
- [x] [DMN Editor] Fix relationship with property link
- [x] DMN Elements [DMN Editor] IDs change when DMN File is persisted
- - [x] Decision Table Rules (IDs are not managed in React)
- - [x] Function
- - [x] Literal Expression, Context, Relation, Invocation & List
- [x] (Luiz) DMN Runner
- - [x] Switching between files should keep the Table/Form open, depending on what was open before.
- - [x] Keydown events on DMN Runner table should not be propagated to the rest of KIE Sandbox.
- - [x] Ensure DMN Runner Table UX is the same as in the Decision Table on DMN Editor. e.g. ESC shortcut, commit edits after enter, trigger select field on enter
- - [x] The BeeTable keyboard shortcuts are triggered while editing a DMN Runner Table cell;
- - [x] Changing input type should erase the input;
- - [x] DMN Runner outputs column should change its type after changing decision node type;
- - [x] DMN Runner table headers should display the correct data types. E.g. ('days and time duration')
- - [x] Differentiate between isActive and isEditing when navigating on BeeTable.
- [x] Autofilling nested expressions doesn't work in some scenarios

## KNOWN ISSUES

Issues that are currently identified on Boxed Expression Editor, and should be fixed. Most of them are bugs and do not prevent users from authoring expressions, though.

##### General:

- [x] Fix yard-related packages. They're not compiling after changes on BEE.
- [x] yard now correctly compiles and builds, but the integration seems not fully implemented. (Decision table rows data doesn't show, but that issue is present in `main` as well - no regressions)
- [x] Fix/delete unit tests.
- [x] Fix IT tests.

##### Resizing:

- [x] Java function type weird behavior when resizing
- [x] DecisionTable/Relation delete columns resizing bug.
- [x] Double-clicking the resizeHandler of a table header cell should change with to fit data.
- [x] Revisit `WidthMaths.ts` after removing `@patternfly/react-table`. There are 1px too much everywhere.
- [x] Resizing table columns when the container is already at minWidth.
- [x] Add resizer handles to all column headers.
- [x] Resizing a FEEL Function implementation only works after the second click on the resize handle, for any type of nested expression.
- [x] It shouldn't be possible to resize the label columns on PMML Functions. The same we do for JAVA Functions.

##### Keyboard:

- [x] Arrow-right on upper headers goes beyond the limit. Limit is correct using headerGroups.

##### Copy/cut/paste:

- [x] Allow pasting arbitrary data on cells that contain literal expressions.

##### Input:

- [x] Can't edit by start typing after pressing backspace on a cell, without pressing Enter.
- [x] Closing HitPolicy selector without pressing Esc (e.g. clicking outside) breaks keyboard shortcuts like Backspace, Ctrl+C etc.
- [x] Resizing columns triggers selection. Sometimes at the right-side, but always at top or bottom.
- [x] FEEL Input onBlur not working. Typing a value and clicking outside does not save the typed value.
- [x] Pressing `Esc` when editing an Annotations column name breaks the keyboard navigation.
- [x] When editing a Relation/DT cell, if you click outside it (blur) to set the value, it only works if the clicked cell is to the left or above the active cell.
- [x] Selection bug when adding/deleting rows/column.

##### UX:

- [x] Pasting expressions error handling. Must be done right at the menu. No modals/popovers.
- [x] HitPolicy selector should not close the Popover when selecting values on the Selects.
- [x] When double-clicking a column resize handler, resize it to fit to data.

##### UI:

- [x] Ctrl+ and Ctrl- zoom problems. Zoom in and out.
- [x] FEEL expressions highlight is wrong. E.g. "anything" -> "in" is blue, rest is black.
- [x] Add empty state to parameters popover on Function expressions.
- [x] Add icons to FunctionKind selector. (FEEL, Java, and PMML)
- [x] Better labels for HitPolicy selector. All of them should have a good short description too.
- [x] Better labels for FunctionKind selector. All of them should have a good short description too.
- [x] Add description to all expression types, right at the `Select expression` menu.

### On DMN Editor:

- [x] Keyboard shortcuts are not working.
- [x] Undo/Redo
- - [x] Re-enable Undo/Redo experience
- - [x] Doesn't work when resizing the Table
- - [x] TypeRef (and TypeRef holder) updates from react are not correctly managed in the case of Custom Types
- - [x] Undo/Redo doesn't work correctly when resetting an expression
- - [x] Autofilling root expressions based on Data Types
- - [x] Propagate expression updates in React only if the Expression actually changes.
- - [x] Undo/Redo for clear expression actions throws an exception
- - [x] DMN Elements IDs change during UNDO/REDO actions
- - [x] Undo/Redo doesn't work as expected in BKM nodes (It reproduces in the previous React BEE version as well)
- - [x] Redo a resizing doesn't work in some scenarios (e.g. Context expression with nested expressions)
- [x] Removing auto-filling ContextEntry items with Literal Expression with null value and comment
- [x] Basic Autofilling nested expressions based on Data Types (Same capabilities of current GWT-based BEE)
- [x] Check this -> https://github.com/kiegroup/kie-issues/issues/42
- [x] Marshaller fails with undefined nested expression in List
- [x] Synchronization between old and new editors.
- [x] Fix integration tests

### On DMN Runner:

- [x] Context Menu is appearing too far from the clicked place.
- [x] Keyboard shortcuts are not working.
- [x] Infinite loop happening when rendering the table.
- [x] Input cells are losing focus after input.
- [x] Deleting a line doesn't work.
- [x] `setRows(prev => {})` is not behaving well. DmnRunnerInputs should be able to provide the correct `prev` variable like setters of `useState` do. This impacts pasting/reseting cells, as only changes to the last impacted row are being persisted.
- [x] Column widths are not being persisted.

### PR DESCRIPTION
**Pull request by tiagobento**
Closes https://github.com/kiegroup/kie-issues/issues/87

---

Several improvements were made to the DMN Boxed Expression Editor (BEE) on this PR. We're aware it's very big, and we don't plan to have such a big PR coming again anytime soon :)

HUGE thanks to everyone involved in this work, especially @yesamer, @jomarko, @ljmotta, and @danielzhe!

A running version of it can be found at https://tiagobento.github.io/prototypes/kie-sandbox--with-bee-refactor

Here's a GIF showcasing the changes made to the BEE.

https://user-images.githubusercontent.com/1584568/234365593-b783d2cd-20c6-4a51-9442-fed0371466c3.mov

---

Updates include:
- Completely redesigned state management
- Brand new selection and keyboard navigation mechanisms inspired by Google Sheets
- Resizing improvements regarding minWidth constraints and proportional resizing of nested multi-column boxed expressions.
- New buttons for inline adding rows and columns
- Copy/cut/paste actions for entire expressions, making it easier to refactor big boxed expressions.
- New inline descriptions for boxed expressions types, hit policies on Decision Tables, and Function kinds.
- And many more little quality of life improvements you'll be able to see when using it.
- The DMN Runner table also benefits from this refactoring, including selection and navigation.

We're not stopping here. This is only the beginning! Below you can see a snapshot of the issues that we plan to add in the short/medium term.

## SHORT TERM:

- General
  - https://github.com/kiegroup/kie-issues/issues/172
  - https://github.com/kiegroup/kie-issues/issues/162
  - https://github.com/kiegroup/kie-issues/issues/163
  - https://github.com/kiegroup/kie-issues/issues/34
- Resizing
  - https://github.com/kiegroup/kie-issues/issues/178
  - https://github.com/kiegroup/kie-issues/issues/179
  - https://github.com/kiegroup/kie-issues/issues/180
  - https://github.com/kiegroup/kie-issues/issues/181
- Input
  - https://github.com/kiegroup/kie-issues/issues/210
  - https://github.com/kiegroup/kie-issues/issues/182
  - https://github.com/kiegroup/kie-issues/issues/183
  - https://github.com/kiegroup/kie-issues/issues/184
  - https://github.com/kiegroup/kie-issues/issues/185
  - https://github.com/kiegroup/kie-issues/issues/187
  - https://github.com/kiegroup/kie-issues/issues/186
  - https://github.com/kiegroup/kie-issues/issues/214
  - https://github.com/kiegroup/kie-issues/issues/222
  - https://github.com/kiegroup/kie-issues/issues/223
  - https://github.com/kiegroup/kie-issues/issues/252
- Context menu
  - https://github.com/kiegroup/kie-issues/issues/168
  - https://github.com/kiegroup/kie-issues/issues/216
  - https://github.com/kiegroup/kie-issues/issues/259
  - https://github.com/kiegroup/kie-issues/issues/272
- DMN Editor
  - https://github.com/kiegroup/kie-issues/issues/113
  - https://github.com/kiegroup/kie-issues/issues/188
  - https://github.com/kiegroup/kie-issues/issues/250
  - https://github.com/kiegroup/kie-issues/issues/255
  - https://github.com/kiegroup/kie-issues/issues/278
- DMN Runner
  - https://github.com/kiegroup/kie-issues/issues/166
  - https://github.com/kiegroup/kie-issues/issues/177
  - https://github.com/kiegroup/kie-issues/issues/176
  - https://github.com/kiegroup/kie-issues/issues/175
  - https://github.com/kiegroup/kie-issues/issues/174
  - https://github.com/kiegroup/kie-issues/issues/173
  - https://github.com/kiegroup/kie-issues/issues/167
  - https://github.com/kiegroup/kie-issues/issues/225
  - https://github.com/kiegroup/kie-issues/issues/226
  - https://github.com/kiegroup/kie-issues/issues/228
  - https://github.com/kiegroup/kie-issues/issues/229
  - https://github.com/kiegroup/kie-issues/issues/230
  - https://github.com/kiegroup/kie-issues/issues/253
  - https://github.com/kiegroup/kie-issues/issues/265

## MEDIUM TERM:

- UX
  - https://github.com/kiegroup/kie-issues/issues/191
  - https://github.com/kiegroup/kie-issues/issues/192
  - https://github.com/kiegroup/kie-issues/issues/193
  - https://github.com/kiegroup/kie-issues/issues/194
  - https://github.com/kiegroup/kie-issues/issues/211
- Copy/paste
  - https://github.com/kiegroup/kie-issues/issues/195
  - https://github.com/kiegroup/kie-issues/issues/196
  - https://github.com/kiegroup/kie-issues/issues/170
  - https://github.com/kiegroup/kie-issues/issues/217
- Resizing
  - https://github.com/kiegroup/kie-issues/issues/197
  - https://github.com/kiegroup/kie-issues/issues/198
  - https://github.com/kiegroup/kie-issues/issues/199
  - https://github.com/kiegroup/kie-issues/issues/200
  - https://github.com/kiegroup/kie-issues/issues/204
  - https://github.com/kiegroup/kie-issues/issues/190
  - https://github.com/kiegroup/kie-issues/issues/189
- Refactoring
  - https://github.com/kiegroup/kie-issues/issues/209
  - https://github.com/kiegroup/kie-issues/issues/208
- FEEL Language Service
  - https://github.com/kiegroup/kie-issues/issues/205
  - https://github.com/kiegroup/kie-issues/issues/207
  - https://github.com/kiegroup/kie-issues/issues/206
  - https://github.com/kiegroup/kie-issues/issues/159
- Code improvements
  - https://github.com/kiegroup/kie-issues/issues/169 
- Selection
  - https://github.com/kiegroup/kie-issues/issues/203
- Performance
  - https://github.com/kiegroup/kie-issues/issues/202
  - https://github.com/kiegroup/kie-issues/issues/215
- SceSim
  - https://github.com/kiegroup/kie-issues/issues/201

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -141,6 +141,7 @@ packages/stunner-editors/**/src/main/webapp/WEB-INF/lib/
 packages/stunner-editors/**/src/main/webapp/WEB-INF/model/
 packages/stunner-editors/**/src/main/webapp/model/
 packages/stunner-editors/**/kie-wb-common-dmn-webapp
+packages/stunner-editors/.idea
```
Comment (yesamer) [inline .gitignore:144]: @tiagobento Minor: We could better manage this in the `# User-specific stuff` (line 188)

File: examples/uniforms-patternfly/src/schemas/json-schema.ts [hunk 2]
```diff
@@ -51,9 +51,10 @@ const schema = {
         arrival: {
           type: "string",
           format: "date-time",
+          max: "2000-04-04T10:30:00.000Z",
```
Comment (yesamer) [inline examples/uniforms-patternfly/src/schemas/json-schema.ts:54]: @tiagobento is that intentional? Happy because that's my birthday! :D

File: packages/boxed-expression-component/README.md [hunk 3]
```diff
@@ -16,7 +16,7 @@ In the `showcase` folder, there is a tiny React application, which represent the
 Once the showcase application gets launched, you can see on the right side of the page the JSON that is actually produced for the corresponding selected logic type.
```
Comment (yesamer) [inline packages/boxed-expression-component/README.md:16]: @tiagobento We should revisit this README file (eg. see line 7, that can be removed)

File: packages/boxed-expression-component/showcase/defaultExpression.ts [hunk 4]
```diff
@@ -0,0 +1,254 @@
...
+  RelationExpressionDefinition,
+  DecisionTableExpressionDefinition,
+  DecisionTableExpressionDefinitionHitPolicy,
+  DecisionTableExpressionDefinitionBuiltInAggregation,
+  ExpressionDefinitionBase,
+} from "../src/api";
+import {
+  LITERAL_EXPRESSION_MIN_WIDTH,
+  CONTEXT_ENTRY_INFO_MIN_WIDTH,
+  RELATION_EXPRESSION_COLUMN_DEFAULT_WIDTH,
```
Comment (yesamer) [inline packages/boxed-expression-component/showcase/defaultExpression.ts]: @tiagobento Unused

File: packages/boxed-expression-component/showcase/index.tsx [hunk 5]
```diff
@@ -15,27 +15,22 @@
...
 } from "../src/api";
-import { BoxedExpressionEditor } from "../src/components";
+import { BoxedExpressionEditor } from "../src/expressions";
+import { getDefaultExpressionDefinitionByLogicType } from "./defaultExpression";
 import { Button } from "@patternfly/react-core/dist/js/components/Button";
 import { Modal } from "@patternfly/react-core/dist/js/components/Modal";
 import { PenIcon } from "@patternfly/react-icons/dist/js/icons/pen-icon";
-import "../src/components/BoxedExpressionEditor/base-no-reset-wrapped.css";
+import "../src/expressions/BoxedExpressionEditor/base-no-reset-wrapped.css";
 import ReactJson from "react-json-view";
```
Comment (yesamer) [inline packages/boxed-expression-component/showcase/index.tsx:34]: @tiagobento It seems unused.

File: packages/boxed-expression-component/showcase/index.tsx [hunk 6]
```diff
@@ -15,27 +15,22 @@
...
-  LogicType,
-  RelationProps,
+  BeeGwtService,
+  DmnBuiltInDataType,
+  ExpressionDefinitionLogicType,
+  ExpressionDefinition,
+  generateUuid,
 } from "../src/api";
-import { BoxedExpressionEditor } from "../src/components";
+import { BoxedExpressionEditor } from "../src/expressions";
```
Comment (yesamer) [inline packages/boxed-expression-component/showcase/index.tsx:28]: @tiagobento It seems unused.

File: packages/boxed-expression-component/showcase/index.tsx [hunk 7]
```diff
@@ -82,77 +77,74 @@ export const pmmlParams = [
...
-    broadcastDecisionTableExpressionDefinition: (definition: DecisionTableProps) => setExpressionDefinition(definition),
-    notifyUserAction(): void {},
-    openManageDataType(): void {},
-    onLogicTypeSelect(): void {},
-    selectObject(): void {},
-  };
-
-  const onTypedExpressionChange = useCallback((e) => {
-    setTypedExpressionDefinition(e.target.value);
+  const onExpressionStringChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
```
Comment (yesamer) [inline packages/boxed-expression-component/showcase/index.tsx:114]: @tiagobento In this code block, it seems there are some unused functions and useState variables.

**Review by yesamer — COMMENTED** [review]
(Quick) code review -First round

File: packages/boxed-expression-component/src/api/Bee.ts [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+import _ from "lodash";
+import {
+  ContextExpressionDefinition,
+  DecisionTableExpressionDefinition,
+  ExpressionDefinition,
```
Comment (yesamer) [inline packages/boxed-expression-component/src/api/Bee.ts]: @tiagobento "ExpressionDefinition" is the only import used.

File: packages/boxed-expression-component/src/api/ExpressionDefinition.ts [hunk 9]
```diff
@@ -0,0 +1,295 @@
...
+
+export interface PmmlParam {
+  document: string;
+  modelsFromDocument?: {
+    model: string;
+    parametersFromModel?: ContextExpressionDefinitionEntryInfo[];
+  }[];
+}
+
+// FIXME: Tiago -> Move
```
Comment (yesamer) [inline packages/boxed-expression-component/src/api/ExpressionDefinition.ts]: @tiagobento Is this comment still needed?

File: packages/boxed-expression-component/src/contextMenu/MenuWithHelp/MenuItemWithHelp.tsx [hunk 10]
```diff
@@ -0,0 +1,57 @@
+import * as React from "react";
```
Comment (yesamer) [inline packages/boxed-expression-component/src/contextMenu/MenuWithHelp/MenuItemWithHelp.tsx:17]: @tiagobento Copyright prefix is missing

File: packages/boxed-expression-component/src/contextMenu/MenuWithHelp/MenuWithHelp.css [hunk 11]
```diff
@@ -0,0 +1,20 @@
+.menu-item-with-help .pf-c-menu__item {
```
Comment (yesamer) [inline packages/boxed-expression-component/src/contextMenu/MenuWithHelp/MenuWithHelp.css:17]: @tiagobento Copyright prefix is missing

File: packages/boxed-expression-component/src/contextMenu/Hooks.ts [hunk 12]
```diff
@@ -0,0 +1,134 @@
...
+  xPos: string;
+  yPos: string;
+  isOpen: boolean;
+} {
+  const { setCurrentlyOpenContextMenu, currentlyOpenContextMenu, editorRef, scrollableParentRef } =
+    useBoxedExpressionEditor();
+
+  const [scroll, setScroll] = useState({ x: 0, y: 0 });
+
+  // FIXME: Tiago -> Need to calculate the context menu length for it to not be hidden by the borders of the screen.
```
Comment (yesamer) [inline packages/boxed-expression-component/src/contextMenu/Hooks.ts]: @tiagobento Please check this FIXME

File: packages/boxed-expression-component/src/expressions/BoxedExpressionEditor/BoxedExpressionEditorContext.tsx [hunk 13]
```diff
@@ -0,0 +1,131 @@
...
+      setExpression: setExpressionDefinition,
+    }),
+    [setExpressionDefinition]
+  );
+
+  return (
+    <BoxedExpressionEditorContext.Provider
+      value={{
+        //plumbing
+        beeGwtService, // FIXME: Tiago -> Move to a separate context
```
Comment (yesamer) [inline packages/boxed-expression-component/src/expressions/BoxedExpressionEditor/BoxedExpressionEditorContext.tsx]: @tiagobento Please check this FIXME

File: packages/boxed-expression-component/src/expressions/BoxedExpressionEditor/BoxedExpressionEditorContext.tsx [hunk 14]
```diff
@@ -0,0 +1,131 @@
...
+        editorRef,
+        scrollableParentRef,
+
+        // props
+        decisionNodeId,
+        dataTypes,
+        pmmlParams,
+
+        //state // FIXME: Tiago -> Move to a separate context
```
Comment (yesamer) [inline packages/boxed-expression-component/src/expressions/BoxedExpressionEditor/BoxedExpressionEditorContext.tsx]: @tiagobento Please check this FIXME

File: packages/unitables/src/uniforms/UnitablesJsonSchemaBridge.tsx [hunk 15]
```diff
@@ -0,0 +1,159 @@
...
+      field.direction = SelectDirection.up;
+      field.menuAppendTo = document.body;
+    } else if (!field.type) {
+      field.type = "string";
+    }
+    return field;
+  }
+
+  public getFieldDataType(field: Record<string, any>) {
+    const xDmnType: string | undefined = field["x-dmn-type"]; // FIXME: Luiz - shouldn't have any reference to DMN!
```
Comment (yesamer) [inline packages/unitables/src/uniforms/UnitablesJsonSchemaBridge.tsx]: @tiagobento Please check this FIXME

File: packages/boxed-expression-component/src/api/Bee.ts (hunk 8 above)
Comment (yesamer) [reply packages/boxed-expression-component/src/api/Bee.ts]: Fixed

File: packages/boxed-expression-component/src/contextMenu/MenuWithHelp/MenuItemWithHelp.tsx (hunk 10 above)
Comment (yesamer) [reply packages/boxed-expression-component/src/contextMenu/MenuWithHelp/MenuItemWithHelp.tsx:17]: Fixed

File: packages/boxed-expression-component/src/contextMenu/MenuWithHelp/MenuWithHelp.css (hunk 11 above)
Comment (yesamer) [reply packages/boxed-expression-component/src/contextMenu/MenuWithHelp/MenuWithHelp.css:17]: Fixed

File: packages/boxed-expression-component/showcase/index.tsx (hunk 7 above)
Comment (yesamer) [reply packages/boxed-expression-component/showcase/index.tsx:114]: They are used - ignoring.

File: packages/boxed-expression-component/showcase/index.tsx (hunk 6 above)
Comment (yesamer) [reply packages/boxed-expression-component/showcase/index.tsx:28]: They are used - ignoring.

File: packages/boxed-expression-component/showcase/index.tsx (hunk 5 above)
Comment (yesamer) [reply packages/boxed-expression-component/showcase/index.tsx:34]: They are used - ignoring.

File: packages/boxed-expression-component/showcase/defaultExpression.ts (hunk 4 above)
Comment (yesamer) [reply packages/boxed-expression-component/showcase/defaultExpression.ts]: Removed.

File: packages/boxed-expression-component/src/api/ExpressionDefinition.ts (hunk 9 above)
Comment (yesamer) [reply packages/boxed-expression-component/src/api/ExpressionDefinition.ts]: A review of FIXME is in progress - Removing the comment.

File: packages/boxed-expression-component/src/contextMenu/Hooks.ts (hunk 12 above)
Comment (yesamer) [reply packages/boxed-expression-component/src/contextMenu/Hooks.ts]: A review of FIXME is in progress - Removing the comment.

File: packages/boxed-expression-component/src/expressions/BoxedExpressionEditor/BoxedExpressionEditorContext.tsx (hunk 13 above)
Comment (yesamer) [reply packages/boxed-expression-component/src/expressions/BoxedExpressionEditor/BoxedExpressionEditorContext.tsx]: A review of FIXME is in progress - Removing the comment.

File: packages/boxed-expression-component/src/expressions/BoxedExpressionEditor/BoxedExpressionEditorContext.tsx (hunk 14 above)
Comment (yesamer) [reply packages/boxed-expression-component/src/expressions/BoxedExpressionEditor/BoxedExpressionEditorContext.tsx]: A review of FIXME is in progress - Removing the comment.

File: packages/unitables/src/uniforms/UnitablesJsonSchemaBridge.tsx (hunk 15 above)
Comment (yesamer) [reply packages/unitables/src/uniforms/UnitablesJsonSchemaBridge.tsx]: A review of FIXME is in progress - Removing the comment.

File: examples/uniforms-patternfly/src/schemas/json-schema.ts (hunk 2 above)
Comment (ljmotta) [reply examples/uniforms-patternfly/src/schemas/json-schema.ts:54]: @yesamer I choose this date at random hahaha
