### PR TITLE
kie-issues#1679 : If the bottom of the overlay panel is close to editor bottom, it adds a vertical overflow after toggling an option

### LINKED ISSUE #1679: DMN Editor: If the bottom of the overlay panel is close to editor bottom, it adds a vertical `overflow` after toggling an option
In the DMN Editor, if the bottom of the overlay panel is close to the bottom of the DMN Editor, toggling an overlay option will add the vertical overflow to the panel.

To reproduce, it's possible to zoom in the browser:

https://github.com/user-attachments/assets/65fb1b31-47fc-416d-b0e2-043efb4e8801

### PR DESCRIPTION
**Pull request by Kusuma04-dev**
closes https://github.com/apache/incubator-kie-issues/issues/1679 - If the bottom of the overlay panel is close to editor bottom, it adds a vertical overflow after toggling an option

### CODE REVIEW

**Review by jomarko — COMMENTED** [review]
Thank you for the PR. I am not sure what should be my review (approve/not appprove) because:

On m machine by default the scrollbar is needed. Since the ticket was created, we added an entry into overlay panel (evaluation highlights) and also this maybe related to:
- user screen resolution
- browser setup, for example I am using tabs in the top , so the space for webpage is smaller

In other words, in my setup the scrollbar is not needed only if I turn browser into full screen mode.

Screenshot 2025-01-10 090626

**Comment by ljmotta** [comment]
@jomarko Please zoom out to see the issue.
@Kusuma04-dev I still see the issue here in my machine. Please, remember that the overlay panel should be **_close_** to the bottom end of the editor.

**Comment by Kusuma04-dev** [comment]
> @jomarko Please zoom out to see the issue. @Kusuma04-dev I still see the issue here in my machine. Please, remember that the overlay panel should be **_close_** to the bottom end of the editor.

Hi @ljmotta , Can you please check it once and if it is still there we can connect once to see the issue as i am not seeing the issue on my machine now.

**Comment by jomarko** [comment]
@ljmotta should I use browser zoom feature or editor zoom feature?

**Comment by ljmotta** [comment]
@Kusuma04-dev Which browser are you using? Maybe you can't reproduce because of that. Now, the behavior is different.


https://github.com/user-attachments/assets/8fdaa9e7-683a-4fd1-ab63-570b0b05bb56

**Comment by Kusuma04-dev** [comment]
closed by https://github.com/apache/incubator-kie-tools/pull/2845

**Comment by yesamer** [comment]
> closed by #2845

Hey @Kusuma04-dev, you don't need this comment to link this PR with the ticket. You just need to write in the description 
`Closes <link-to-the-ticket>` or `Fixes <link-to-the-ticket>`
as you correctly did and still present in the Description.

**Comment by ljmotta** [comment]
@Kusuma04-dev Could you please add a video of the current solution?

**Comment by Kusuma04-dev** [comment]
> @Kusuma04-dev Could you please add a video of the current solution?


Uploading Screen Recording 2025-01-19 at 8.01.55 PM (1) (1).mov…

**Comment by Kusuma04-dev** [comment]
> > @Kusuma04-dev Could you please add a video of the current solution?
> 

https://github.com/user-attachments/assets/c8c8f93e-8355-4543-a5cb-9f14bf06cfb5

File: packages/dmn-editor/src/overlaysPanel/OverlaysPanel.tsx [hunk 1]
```diff
@@ -43,17 +43,19 @@ export function OverlaysPanel({ availableHeight }: OverlaysPanelProps) {
...
+        if (overlayPanelContainer.current.style.height !== "auto") {
+          overlayPanelContainer.current.style.overflowY = "hidden";
+          overlayPanelContainer.current.style.height = "auto";
+        }
       } else {
-        overlayPanelContainer.current.style.overflowY = "visible";
+        if (overlayPanelContainer.current.style.height !== availableHeight - BOTTOM_MARGIN + "px") {
+          overlayPanelContainer.current.style.height = availableHeight - BOTTOM_MARGIN + "px";
+          overlayPanelContainer.current.style.overflowY = "auto";
+        }
```
Comment (ljmotta) [inline packages/dmn-editor/src/overlaysPanel/OverlaysPanel.tsx]: As we don't have any other condition inside the `if` and `else` we could put all conditions in just one:

```
if (overlayPanelContainer.current.scrollHeight <= availableHeight && overlayPanelContainer.current.style.height !== "auto") {
...
} else if (overlayPanelContainer.current.style.height !== availableHeight - BOTTOM_MARGIN + "px") {
...
}

**Review by ljmotta — CHANGES_REQUESTED** [review]
@Kusuma04-dev The change is working! I've added a last comment inline.

**Review by ljmotta — APPROVED** [review]

**Review by yesamer — APPROVED** [review]
