### PR TITLE
kie-tools#1273: Remove hardcoded children count for data tyle list view

### LINKED ISSUE #1273: Editor: <dmn:itemDefinition> with more than 10 <dmn:itemComponent> appears in other section on the UI
**Describe the Bug**

After adding more than 10 items under a Data Type, the child elements appear expanded over other data types.

**Steps to Reproduce**

1. Open a DMN on the Editor VSCode/Kie sandbox;
2. Go to Data Types;
3. Add more than 10 items;
4. Go to the Editor;
5. Go back to Data Types;
6. You will see the items going over other types;

image

I created a repo with a sample with this problem [Traffic Violation - Many items.dmn](https://github.com/KaueReinbold/dmn-quarkus-example/blob/main/src/main/resources/Traffic%20Violation%20-%20Many%20items.dmn).

**Expected Behavior**

The Data Types should be properly organized to be accessed. 

**Environment**

- OS: Windows
- Visual Studio Code version: 1.71.2
- DMN Editor plugin: 0.23.0
- Language Support for Java(TM) by Red Hat v1.11.0

### PR DESCRIPTION
**Pull request by jomarko**
Closes https://github.com/kiegroup/kie-tools/issues/1273

The mechanism for expanding a DMN data type didn't take into account scenarios with more than 10 Fields of a Structure

### CODE REVIEW

**Comment by jomarko** [comment]
### Manual test checklist
- [x] 3 structures, all collapsed, expand the first one
- [x] 3 structures, all collapsed, expand the second one
- [x] 3 structures, all collapsed, expand the third one
- [x] 3 structures, all expanded, collapse the first one
- [x] 3 structures, all expanded, collapse the second one
- [x] 3 structures, all expanded, collapse the third one
- [x] 3 structures with more than one nested level, all collapsed, expand first one
- [x] 3 structures with more than one nested level, all collapsed, expand second one
- [x] 3 structures with more than one nested level, all collapsed, expand third one
- [x] 3 structures with more than one nested level, all expanded, collapse first one
- [x] 3 structures with more than one nested level, all expanded, collapse second one
- [x] 3 structures with more than one nested level, all expanded, collapse third one

**Comment by jomarko** [comment]
#### 3 structures
```
<dmn:definitions xmlns:dmn="http://www.omg.org/spec/DMN/20180521/MODEL/" xmlns="https://kiegroup.org/dmn/_5EB54AAF-5717-4D88-894B-CD953950400D" xmlns:feel="http://www.omg.org/spec/DMN/20180521/FEEL/" xmlns:kie="http://www.drools.org/kie/dmn/1.2" xmlns:dmndi="http://www.omg.org/spec/DMN/20180521/DMNDI/" xmlns:di="http://www.omg.org/spec/DMN/20180521/DI/" xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/" id="_06B3AFF2-2100-468D-A480-98C8A74B6A03" name="87F9A490-464D-436D-89AB-795885ABDCFD" typeLanguage="http://www.omg.org/spec/DMN/20180521/FEEL/" namespace="https://kiegroup.org/dmn/_5EB54AAF-5717-4D88-894B-CD953950400D">
  <dmn:extensionElements/>
  <dmn:itemDefinition id="_5193CB97-FC0A-495D-9975-7908BF4F28A8" name="Insert a name" isCollection="false">
    <dmn:itemComponent id="_ABB44D62-A845-4926-9A84-878B3BF434A5" name="Insert a name - 15" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_64EECBA7-F67D-4A90-B98F-82BD66FFBECA" name="Insert a name - 14" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_AC40188F-9593-47A8-A199-0B725F060890" name="Insert a name - 13" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_0C221F04-4564-4CA2-9771-964D57F6B26F" name="Insert a name - 12" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_F081070A-F3D5-4BB5-A277-0301D7625261" name="Insert a name - 11" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_7CBDE7B4-7470-4974-BA1B-BCEF8189F2DB" name="Insert a name - 10" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_29F6C589-54CA-4F3C-90BD-06BEAEA7A634" name="Insert a name - 9" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_0DED4B65-FC19-4EF8-A926-533308F7AF7F" name="Insert a name - 8" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_AC840493-F1E1-471C-B6F6-85E68C6E2E65" name="Insert a name - 7" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_D5FFADA7-F224-458D-B83D-1959EB3E113E" name="Insert a name - 6" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_7569C72D-80FA-4BBA-A025-A39B279B65B7" name="Insert a name - 5" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_472341F4-ABA5-4D77-B195-92F42AB2D7D7" name="Insert a name - 4" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_71E2B4EA-DF37-4583-AF13-F1E668428713" name="Insert a name - 3" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_14F55578-F43C-4778-ADD3-53BA3C80B9A2" name="Insert a name - 2" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_E63FC8A5-4859-4D2F-9DB6-69D6767FE811" name="Insert a name" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
  </dmn:itemDefinition>
  <dmn:itemDefinition id="_7843CEE2-E9DC-46AB-8788-178C18298990" name="Insert a name - 2" isCollection="false">
    <dmn:itemComponent id="_B22A73FA-042A-411B-9BAF-E1463F3DA7FB" name="Insert a name - 15" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_225A421D-AB83-4622-B473-A09A9F158819" name="Insert a name - 14" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_0A160729-9159-4D8E-8CF8-7F13B435A496" name="Insert a name - 13" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_70720F75-9705-447C-819F-C867D68065A0" name="Insert a name - 12" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_00F7C74E-4C6A-4B2B-AF3D-DC73637FAB42" name="Insert a name - 11" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_C4860F89-2DF1-4B6B-8B76-10BBCA2FD805" name="Insert a name - 10" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_C9CB6DF6-67B8-4CAA-8858-374E6792D421" name="Insert a name - 9" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_537F2024-121A-417C-94F5-F37D972BE59E" name="Insert a name - 8" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_F4C4C1F4-B9DE-456F-A6E1-69C84F617828" name="Insert a name - 7" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_24E18716-5931-4977-B1F8-3418CD540481" name="Insert a name - 6" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_4E8E0944-0E22-4B13-9971-64F1D59E7CC0" name="Insert a name - 5" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_1C4331B8-E215-418A-8699-725579DFC6FE" name="Insert a name - 4" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_8A93D175-9F50-4988-929F-7C6069399B3D" name="Insert a name - 3" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_40374A10-B4FF-4BD8-A9C8-9461DD611956" name="Insert a name - 2" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_D456367A-5E6E-472B-BC33-8076F6828144" name="Insert a name" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
  </dmn:itemDefinition>
  <dmn:itemDefinition id="_79C6856A-2091-4333-9BD6-BE105F20B91C" name="Insert a name - 3" isCollection="false">
    <dmn:itemComponent id="_AD6F78E5-F279-4CB7-8D25-4DC7832C0D66" name="Insert a name - 15" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_FB271267-804F-4180-B79D-2AFF019A6327" name="Insert a name - 14" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_0D4D9B6A-2581-441F-9CF7-B10704F7D6FA" name="Insert a name - 13" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_B457FD45-4A11-45B0-AB93-1DB1A3B8902A" name="Insert a name - 12" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_D0943C76-1F44-495E-938F-50B6F54682FB" name="Insert a name - 11" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_329A0EFC-0CE2-4D3B-B4C5-B21524AC60FC" name="Insert a name - 10" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_FAFC72BC-AB11-4535-A3C0-F20DF7E462A4" name="Insert a name - 9" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_FC714CAA-2A39-4F1F-8B01-B4E0D16595C1" name="Insert a name - 8" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_8AEEAC53-5426-47B7-823C-940792087DF8" name="Insert a name - 7" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_4974F3E7-0D5A-4857-821B-57D41104E8E1" name="Insert a name - 6" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_0ADFCBFA-042A-43AC-9729-47CFA33ECE2E" name="Insert a name - 5" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_2BDD7672-D57F-43EC-9BD2-7CF420F35E02" name="Insert a name - 4" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_E27BEF3B-50D8-4079-B698-3D72F45652DA" name="Insert a name - 3" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_49DB2E59-2102-44B4-A47B-447DCCDD3A36" name="Insert a name - 2" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_444187C6-FC16-40B0-A2CF-8780FB398348" name="Insert a name" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
  </dmn:itemDefinition>
  <dmndi:DMNDI>
    <dmndi:DMNDiagram id="_6F5EFC4B-9F2A-4F9E-858B-8A338851C036" name="DRG">
      <di:extension>
        <kie:ComponentsWidthsExtension/>
      </di:extension>
    </dmndi:DMNDiagram>
  </dmndi:DMNDI>
```

**Comment by jomarko** [comment]
#### 3 structures with nested structures
```
<dmn:definitions xmlns:dmn="http://www.omg.org/spec/DMN/20180521/MODEL/" xmlns="https://kiegroup.org/dmn/_5EB54AAF-5717-4D88-894B-CD953950400D" xmlns:feel="http://www.omg.org/spec/DMN/20180521/FEEL/" xmlns:kie="http://www.drools.org/kie/dmn/1.2" xmlns:dmndi="http://www.omg.org/spec/DMN/20180521/DMNDI/" xmlns:di="http://www.omg.org/spec/DMN/20180521/DI/" xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/" id="_06B3AFF2-2100-468D-A480-98C8A74B6A03" name="87F9A490-464D-436D-89AB-795885ABDCFD" typeLanguage="http://www.omg.org/spec/DMN/20180521/FEEL/" namespace="https://kiegroup.org/dmn/_5EB54AAF-5717-4D88-894B-CD953950400D">
  <dmn:extensionElements/>
  <dmn:itemDefinition id="_5193CB97-FC0A-495D-9975-7908BF4F28A8" name="Insert a name" isCollection="false">
    <dmn:itemComponent id="_3C5E4401-6A66-452A-B74B-43D630C55352" name="Insert a name - 16" isCollection="false">
      <dmn:itemComponent id="_F87CF304-35DC-4042-B41E-4473DD5C1E61" name="Insert a name" isCollection="false">
        <dmn:itemComponent id="_0C020B51-51BD-4111-91AA-7952A958F7EB" name="Insert a name" isCollection="false">
          <dmn:typeRef>Any</dmn:typeRef>
        </dmn:itemComponent>
      </dmn:itemComponent>
    </dmn:itemComponent>
    <dmn:itemComponent id="_ABB44D62-A845-4926-9A84-878B3BF434A5" name="Insert a name - 15" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_64EECBA7-F67D-4A90-B98F-82BD66FFBECA" name="Insert a name - 14" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_AC40188F-9593-47A8-A199-0B725F060890" name="Insert a name - 13" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_0C221F04-4564-4CA2-9771-964D57F6B26F" name="Insert a name - 12" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_F081070A-F3D5-4BB5-A277-0301D7625261" name="Insert a name - 11" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_7CBDE7B4-7470-4974-BA1B-BCEF8189F2DB" name="Insert a name - 10" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_29F6C589-54CA-4F3C-90BD-06BEAEA7A634" name="Insert a name - 9" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_0DED4B65-FC19-4EF8-A926-533308F7AF7F" name="Insert a name - 8" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_AC840493-F1E1-471C-B6F6-85E68C6E2E65" name="Insert a name - 7" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_D5FFADA7-F224-458D-B83D-1959EB3E113E" name="Insert a name - 6" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_7569C72D-80FA-4BBA-A025-A39B279B65B7" name="Insert a name - 5" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_472341F4-ABA5-4D77-B195-92F42AB2D7D7" name="Insert a name - 4" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_71E2B4EA-DF37-4583-AF13-F1E668428713" name="Insert a name - 3" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_14F55578-F43C-4778-ADD3-53BA3C80B9A2" name="Insert a name - 2" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_E63FC8A5-4859-4D2F-9DB6-69D6767FE811" name="Insert a name" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
  </dmn:itemDefinition>
  <dmn:itemDefinition id="_7843CEE2-E9DC-46AB-8788-178C18298990" name="Insert a name - 2" isCollection="false">
    <dmn:itemComponent id="_03849ACB-A8F3-41E6-8D7C-C9D2D3B07604" name="Insert a name - 16" isCollection="false">
      <dmn:itemComponent id="_450089B8-6A16-410B-8008-59312A16883B" name="Insert a name" isCollection="false">
        <dmn:itemComponent id="_1E5403B7-883D-4FE1-80C5-D5EB4B80A6FE" name="Insert a name" isCollection="false">
          <dmn:typeRef>Any</dmn:typeRef>
        </dmn:itemComponent>
      </dmn:itemComponent>
    </dmn:itemComponent>
    <dmn:itemComponent id="_B22A73FA-042A-411B-9BAF-E1463F3DA7FB" name="Insert a name - 15" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_225A421D-AB83-4622-B473-A09A9F158819" name="Insert a name - 14" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_0A160729-9159-4D8E-8CF8-7F13B435A496" name="Insert a name - 13" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_70720F75-9705-447C-819F-C867D68065A0" name="Insert a name - 12" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_00F7C74E-4C6A-4B2B-AF3D-DC73637FAB42" name="Insert a name - 11" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_C4860F89-2DF1-4B6B-8B76-10BBCA2FD805" name="Insert a name - 10" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_C9CB6DF6-67B8-4CAA-8858-374E6792D421" name="Insert a name - 9" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_537F2024-121A-417C-94F5-F37D972BE59E" name="Insert a name - 8" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_F4C4C1F4-B9DE-456F-A6E1-69C84F617828" name="Insert a name - 7" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_24E18716-5931-4977-B1F8-3418CD540481" name="Insert a name - 6" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_4E8E0944-0E22-4B13-9971-64F1D59E7CC0" name="Insert a name - 5" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_1C4331B8-E215-418A-8699-725579DFC6FE" name="Insert a name - 4" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_8A93D175-9F50-4988-929F-7C6069399B3D" name="Insert a name - 3" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_40374A10-B4FF-4BD8-A9C8-9461DD611956" name="Insert a name - 2" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_D456367A-5E6E-472B-BC33-8076F6828144" name="Insert a name" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
  </dmn:itemDefinition>
  <dmn:itemDefinition id="_79C6856A-2091-4333-9BD6-BE105F20B91C" name="Insert a name - 3" isCollection="false">
    <dmn:itemComponent id="_9686F8D5-2DCE-482D-A58B-AB2C7FAB7645" name="Insert a name - 16" isCollection="false">
      <dmn:itemComponent id="_88CCF675-FD23-4F93-AD45-EB9783E3FDAD" name="Insert a name" isCollection="false">
        <dmn:itemComponent id="_C331A9A5-E734-4485-A470-EB2C3952709E" name="Insert a name" isCollection="false">
          <dmn:typeRef>Any</dmn:typeRef>
        </dmn:itemComponent>
      </dmn:itemComponent>
    </dmn:itemComponent>
    <dmn:itemComponent id="_AD6F78E5-F279-4CB7-8D25-4DC7832C0D66" name="Insert a name - 15" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_FB271267-804F-4180-B79D-2AFF019A6327" name="Insert a name - 14" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_0D4D9B6A-2581-441F-9CF7-B10704F7D6FA" name="Insert a name - 13" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_B457FD45-4A11-45B0-AB93-1DB1A3B8902A" name="Insert a name - 12" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_D0943C76-1F44-495E-938F-50B6F54682FB" name="Insert a name - 11" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_329A0EFC-0CE2-4D3B-B4C5-B21524AC60FC" name="Insert a name - 10" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_FAFC72BC-AB11-4535-A3C0-F20DF7E462A4" name="Insert a name - 9" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_FC714CAA-2A39-4F1F-8B01-B4E0D16595C1" name="Insert a name - 8" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_8AEEAC53-5426-47B7-823C-940792087DF8" name="Insert a name - 7" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_4974F3E7-0D5A-4857-821B-57D41104E8E1" name="Insert a name - 6" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_0ADFCBFA-042A-43AC-9729-47CFA33ECE2E" name="Insert a name - 5" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_2BDD7672-D57F-43EC-9BD2-7CF420F35E02" name="Insert a name - 4" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_E27BEF3B-50D8-4079-B698-3D72F45652DA" name="Insert a name - 3" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_49DB2E59-2102-44B4-A47B-447DCCDD3A36" name="Insert a name - 2" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
    <dmn:itemComponent id="_444187C6-FC16-40B0-A2CF-8780FB398348" name="Insert a name" isCollection="false">
      <dmn:typeRef>Any</dmn:typeRef>
    </dmn:itemComponent>
  </dmn:itemDefinition>
  <dmndi:DMNDI>
    <dmndi:DMNDiagram id="_6F5EFC4B-9F2A-4F9E-858B-8A338851C036" name="DRG">
      <di:extension>
        <kie:ComponentsWidthsExtension/>
      </di:extension>
    </dmndi:DMNDiagram>
  </dmndi:DMNDI>
```

File: packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItemViewTest.java [hunk 1]
```diff
@@ -681,6 +682,11 @@ public void testExpand() {
         verify(arrowClassList).remove(RIGHT_ARROW_CSS_CLASS);
         verify(child1.classList).remove(HIDDEN_CSS_CLASS);
         verify(child2.classList).remove(HIDDEN_CSS_CLASS);
+        // item 0 - yPosition: 0
+        // item 1 - yPosition: 1
+        // child1 and child2 yPosition need to be greater than 0 and less than 1
+        verify(presenter).setPositionY(eq(child1), doubleThat(d -> d > 0.3));
```
Comment (yesamer) [inline packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItemViewTest.java]: @jomarko I debugged this test. It seems `childrenCount` you introduced is never initialized, most probably because the related NodeList is not properly mocked. Can you please double check?

**Review by yesamer — COMMENTED** [review]
@jomarko Thank you! Can you please elaborate more on the new algorithm you introduced to determine the correct `y` position please? If I correctly understood, the old algorithm simply adds a `0.1`space shift to every children element.

**Comment by jomarko** [comment]
@yesamer hi, thank you for questions.
re https://github.com/kiegroup/kie-tools/pull/1402#pullrequestreview-1240056704

The screenshot below will help us to understand the issue. The elements in UI has `y` attribute and even more, the elements are sorted vertically using this attribute.

Imagine we will expand `tPassenger`. originally, if we added `0.1` to each its child `y` attribute, we were in situation:
- tPassenger.child1: `y=0.1`
- tPassenger.child2: `y=0.2`
- ...
- tPassenger.child11: `y=1.1` - and here is the problem we have greater value than `tFlight`

`double positionY = parentPositionY + (i.getAndIncrement() / (childrenCount + 1.0));` - should ensure we will never assing last child `y` value greater than next parent sibling.

Screenshot_20230109_092712

File: packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItemViewTest.java (hunk 1 above)
Comment (jomarko) [reply packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItemViewTest.java]: not sure what do you mean, debugging the `testExpand` is like attached on my machine.
Screenshot_20230109_101129

Comment (yesamer) [reply packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItemViewTest.java]: @jomarko Probably is an issue in my local machine, I launched it in IntelliJ and is not defined. Weird.

Comment (yesamer) [reply packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItemViewTest.java]: @jomarko ok please ignore this point. 
In the test, I would add a check that verifies if the calculated y position is < 1 for both elements, according to the new algorithm you introduced.

Comment (jomarko) [reply packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/DataTypeListItemViewTest.java]: @yesamer thank you. Done as 49f144ee

**Review by yesamer — APPROVED** [review]
@jomarko Thank you
