### PR TITLE
kie-issues#3387: DMN Runner missing validation information about the number range 

### LINKED ISSUE #3387: DMN Runner missing validation information about the number range
**Limitation**  
In the DMN Runner panel, when users enter a number outside the allowed range defined in the data type constraints, no validation error or warning is displayed.

This missing feedback causes confusion and can lead to incorrect evaluations, especially in models where number ranges are critical to decision logic.

There is currently no workaround. Users must manually verify the allowed range in the Data Types Editor before entering values in the DMN Runner.

Previously, when a value did not match the declared constraint, the DMN Runner displayed validation information. The expected behavior is that the system should continue to show appropriate validation messages whenever input values fall outside the defined constraints.

Image

### PR DESCRIPTION
**Pull request by rajalakshmys-27**
Closes : [kie-issues#3387](https://github.com/apache/incubator-kie-tools/issues/3387)

Fix for DMN Runner missing validation information about the number range

image (4)

image (5)

### CODE REVIEW

File: packages/uniforms-patternfly/src/wrapField.tsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ filterDOMProps.register(
 
 type WrapperProps = {
   id: string;
-  error?: boolean;
+  error?: boolean | object;
```
Comment (jomarko) [inline packages/uniforms-patternfly/src/wrapField.tsx]: with similar change, I wonder, does backend return still `boolean` in some scenarios? Or from now on it is always object. is this object always somehow unique or it has some known structure?

**Review by jomarko — COMMENTED** [review]
thank you for the pr. I believe your fix works, just trying to understand if both boolezn and object are needed in kie-tools code

File: packages/uniforms-patternfly/src/wrapField.tsx (hunk 1 above)
Comment (rajalakshmys-27) [reply packages/uniforms-patternfly/src/wrapField.tsx]: Thank you for the review.

To clarify, the error type in Uniforms depends on the schema bridge in use:

- With uniforms-bridge-simple-schema-2, error can still be a plain boolean (true), with the actual message provided separately via errorMessage.

- With uniforms-bridge-json-schema (AJV), error is a structured object that follows a known format (instancePath, message, keyword, params, etc.). 

In this PR, the type was updated from boolean | object to boolean | ValidationError. 

This documents the expected AJV shape when present, while still allowing the legacy boolean case. Since the codebase includes both bridges, we need to support both scenarios.

**Review by jomarko — APPROVED** [review]
Thank you for the PR!

**Review by thiagoelg — APPROVED** [review]
