### PR TITLE
kie-issues#2466: Serverless Logic Web Tools: Runtime Tools settings doesn't validate the data index url.

### LINKED ISSUE #2466: Serverless Logic Web Tools: Runtime Tools settings doesn't validate the data index url
The Data Index URL is not validated in https://start.kubesmarts.org/dev/#/settings/runtime-tools

Steps to reproduce:
- https://start.kubesmarts.org/dev/#/settings/runtime-tools
- Click "Add runtime tools information"
- Enter any non valid URL, eg. "http://nonvalid"
- Click Apply
- The URL is accepted

### PR DESCRIPTION
**Pull request by kumaradityaraj**
Closes [apache/incubator/kie-issues#2466](https://github.com/apache/incubator-kie-tools/issues/2466)

**Description:**
The data index url is now validated and if its invalid an alert is shown.

**How to test:**

- Navigate to `serverless-logic-web-tools` package
- Execute the command `pnpm start`
- Click on this link to set your data index url and validate it [Runtime tools settings page](https://localhost:9020/#/settings/runtime-tools)

**Preview:**

https://github.com/user-attachments/assets/a1ce2a91-7185-4a71-a223-4f13c0bb366d

### CODE REVIEW

**Comment by kumaradityaraj** [comment]
@fantonangeli Please review this PR. Thank you.

File: packages/serverless-logic-web-tools/src/settings/runtimeTools/RuntimeToolsSettings.tsx [hunk 1]
```diff
@@ -43,14 +43,28 @@ import {
...
+  INVALID = "INVALID",
+}
+
 export function RuntimeToolsSettings(props: SettingsPageProps) {
+  const { i18n } = useAppI18n();
   const settings = useSettings();
   const settingsDispatch = useSettingsDispatch();
   const [config, setConfig] = useState(settings.runtimeTools.config);
   const [isModalOpen, setIsModalOpen] = useState(false);
+  const [isDataIndexUrlValidated, setDataIndexUrlValidated] = useState(DataIndexValidation.INVALID);
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/settings/runtimeTools/RuntimeToolsSettings.tsx]:
```suggestion
  const [isDataIndexUrlValidated, setDataIndexUrlValidated] = useState(DataIndexValidation.INITIAL);
```

File: packages/serverless-logic-web-tools/src/settings/runtimeTools/RuntimeToolsSettings.tsx [hunk 2]
```diff
@@ -43,14 +43,28 @@ import {
   saveConfigCookie,
 } from "./RuntimeToolsConfig";
 import { removeTrailingSlashFromUrl } from "../../url";
+import { validDataIndexUrl } from "../../url";
+import { Alert } from "@patternfly/react-core/dist/js";
+import { useAppI18n } from "../../i18n";
 
 const PAGE_TITLE = "Runtime Tools";
 
+enum DataIndexValidation {
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/settings/runtimeTools/RuntimeToolsSettings.tsx]: XXS suggestion. On some pages we call this `FormValiationOptions`, we can make this name consistent with those pages:
packages/serverless-logic-web-tools/src/settings/openshift/OpenShiftSettingsSimpleConfig.tsx
packages/online-editor/src/accounts/kubernetes/ConnectToKubernetesSimple.tsx
packages/online-editor/src/accounts/openshift/ConnecToOpenShiftSimple.tsx

```suggestion
enum FormValiationOptions {
```

File: packages/serverless-logic-web-tools/src/i18n/AppI18n.ts [hunk 3]
```diff
@@ -71,6 +71,7 @@ interface AppDictionary extends ReferenceDictionary {
       validationError: string;
       connectionError: string;
       configExpiredWarning: string;
+      validDataIndexURLError: string;
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/i18n/AppI18n.ts]: Thank you for taking care of the translations.
This section is related to the OpenShift settings page.
I suggest creating a section for RuntimeToolsSettings page to store this property.
ie: `RuntimeToolsSettings.configModal.validDataIndexURLError`

File: packages/serverless-logic-web-tools/tests/url/dataIndexValidUrl.test.ts [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+
+import { validDataIndexUrl } from "../../src/url";
+
+describe("removeTrailingSlash", () => {
+  it.each([
+    ["http://example.com/", true],
+    ["https://example.com/", true],
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/tests/url/dataIndexValidUrl.test.ts:26]: Let's ensure we accept only http/https protocol.
```suggestion
    ["http://example.com", true],
    ["http://example.com/", true],
    ["https://example.com/", true],
    ["ftps://example.com/", false],
```

File: packages/serverless-logic-web-tools/src/url/index.ts [hunk 5]
```diff
@@ -26,3 +26,12 @@
 export function removeTrailingSlashFromUrl(url: string): string {
   return url.replace(/\/$/, "");
 }
+
+export function validDataIndexUrl(url: string): boolean {
+  try {
+    new URL(url);
+    return true;
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/url/index.ts]: I found a bug here, we are accepting every protocol in this function.

@tiagobento it's out of scope, but do you think we should also reproduce this suggestion here?
https://github.com/kumaradityaraj/kie-tools/blob/fc27f22fa01303a39132ae27494b43a41bc7101f/packages/kubernetes-bridge/src/service/KubernetesConnection.ts#L51

```suggestion
    const parsedUrl = new URL(url);
    return parsedUrl.protocol === "http:" || parsedUrl.protocol === "https:";
```

File: packages/serverless-logic-web-tools/tests/url/dataIndexValidUrl.test.ts [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+    ["loremIpsum", false],
+    ["google.com", false],
+  ])("should validate the data index URL", (inputUrl, isValidUrl) => {
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/tests/url/dataIndexValidUrl.test.ts]: Let's improve the log messages.
```suggestion
  ])("the data index URL %s validation should be %s", (inputUrl, isValidUrl) => {
```

File: packages/serverless-logic-web-tools/src/url/index.ts [hunk 7]
```diff
@@ -26,3 +26,12 @@
 export function removeTrailingSlashFromUrl(url: string): string {
   return url.replace(/\/$/, "");
 }
+
+export function validDataIndexUrl(url: string): boolean {
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/url/index.ts]: We can make this name consistent with the other kie-tools validation functions.
```suggestion
export function isDataIndexUrlValid(url: string): boolean {
```

File: packages/serverless-logic-web-tools/tests/url/dataIndexValidUrl.test.ts [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+ * software distributed under the License is distributed on an
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ * KIND, either express or implied.  See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+
+import { validDataIndexUrl } from "../../src/url";
+
+describe("removeTrailingSlash", () => {
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/tests/url/dataIndexValidUrl.test.ts]: Leftover?

File: packages/serverless-logic-web-tools/src/settings/runtimeTools/RuntimeToolsSettings.tsx [hunk 9]
```diff
@@ -80,6 +94,11 @@ export function RuntimeToolsSettings(props: SettingsPageProps) {
     const newConfig: RuntimeToolsSettingsConfig = {
       dataIndexUrl: removeTrailingSlashFromUrl(config.dataIndexUrl),
     };
+    if (!validDataIndexUrl(config.dataIndexUrl)) {
+      setDataIndexUrlValidated(DataIndexValidation.INVALID);
+      return;
+    }
+
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/settings/runtimeTools/RuntimeToolsSettings.tsx:112]: After checking if it's valid it would be great to really test the url answers to a simple query.
You can use:
https://github.com/apache/incubator-kie-tools/blob/fc27f22fa01303a39132ae27494b43a41bc7101f/packages/sonataflow-deployment-webapp/src/data/index.ts#L33
Maybe we can move `verifyDataIndex()` inside the package `runtime-tools-swf-gateway-api` to avoid code duplication.

**Review by fantonangeli — CHANGES_REQUESTED** [review]
Thank you @kumaradityaraj for your prompt PR.

File: packages/serverless-logic-web-tools/src/settings/runtimeTools/RuntimeToolsSettings.tsx [hunk 10]
```diff
@@ -60,10 +62,12 @@ export function RuntimeToolsSettings(props: SettingsPageProps) {
   const settingsDispatch = useSettingsDispatch();
   const [config, setConfig] = useState(settings.runtimeTools.config);
   const [isModalOpen, setIsModalOpen] = useState(false);
-  const [isDataIndexUrlValidated, setDataIndexUrlValidated] = useState(DataIndexValidation.INVALID);
+  const [isDataIndexUrlValidated, setDataIndexUrlValidated] = useState(FormValiationOptions.INITIAL);
+  const [isDataIndexUrlVerified, setisDataIndexUrlVerified] = useState(FormValiationOptions.INITIAL);
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/settings/runtimeTools/RuntimeToolsSettings.tsx]: Similarily to https://github.com/kumaradityaraj/kie-tools/blob/2709ce4349c467ffba41e2e8f9cbe78c10502333/packages/serverless-logic-web-tools/src/settings/openshift/OpenShiftSettingsSimpleConfig.tsx#L58
Can we use one state, for the validation result?
```suggestion
  const [isConfigValidated, setConfigValidated] = useState(FormValiationOptions.INITIAL);
```

**Review by fantonangeli — CHANGES_REQUESTED** [review]
Only one small suggestion.
Thank you @kumaradityaraj

**Review by fantonangeli — APPROVED** [review]

**Review by thiagoelg — APPROVED** [review]

**Comment by tiagobento** [comment]
There are multiple failures after merging this to `main`.. can you please check @fantonangeli @kumaradityaraj

**Comment by fantonangeli** [comment]
Thanks @tiagobento, I'm checking now
