### PR TITLE
kie-tools-issues#2886 [Serverless Logic Web Tools] NoStackTraceException on the deployment if the workflow has a validation warning

### LINKED ISSUE #2886: [Serverless Logic Web Tools] NoStackTraceException on the deployment if the workflow has a validation warning
If there are errors in the WF you cannot deploy it, but if there are warnings like changing the start node to something wrong ie:
`"start": "NotExistingNode",`

It's possible to deploy the WF and it breaks the deployment showing the following error in the deployment page:
`io.vertx.core.impl.NoStackTraceException` 

**Steps to reproduce:**
- Import the example in this issue or change the `start` node in the Greeting example
- Deploy on devmode on OpenShift (normal deployments are also affected)
- Open the deployment

Full example:
[greeting-with-warning.sw.json](https://github.com/user-attachments/files/18600786/greeting-with-warning.sw.json)

### PR DESCRIPTION
**Pull request by kumaradityaraj**
✨ **Closes [2886](https://github.com/apache/incubator-kie-tools/issues/2886) – Prevent Deployment with Validation Errors**

---

### 🛠️ Summary

This PR enhances the workflow deployment experience by preventing users from deploying workflows that contains validation errors. It ensures proper feedback through UI alerts.

---

### ✅ What’s Fixed

- **Validation Alert on Deployment Attempt**  
  When a user tries to deploy a workflow that contains validation errors, a clear warning is shown:  
  > ⚠️ *"Please resolve validation errors in your workflow."*

- **Danger Alert on Forced Deployment**  
  If the user attempts to bypass the warning and forcefully deploy the workflow:  
  - A **danger alert** is shown:  
    > 🛑 *"Please resolve validation errors in your workflow before deployment."*  
  - The deployment modal is also **automatically closed** to prevent further action.

---

### 📹 Demo

A video showcasing the updated behavior is attached.

https://github.com/user-attachments/assets/ad8406f2-d286-4580-9881-a3af5daf94f6

### CODE REVIEW

**Comment by kumaradityaraj** [comment]
@fantonangeli Please review this PR. Thank you.

File: packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx [hunk 1]
```diff
@@ -201,13 +201,31 @@ export function useDeployDropdownItems(props: Props) {
     [devMode.isEnabled, props.workspaceFile.name]
   );
 
+  const onDeployWarningAlert = useGlobalAlert(
+    useCallback(({ close }) => {
+      return (
+        <Alert
+          className="pf-v5-u-mb-md"
+          variant="warning"
+          title={<>Please resolve validation errors in your workflow.</>}
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx]:
```suggestion
          title={<>Please resolve the validation errors in your workflow.</>}
```

File: packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx [hunk 2]
```diff
@@ -201,13 +201,31 @@ export function useDeployDropdownItems(props: Props) {
...
+    }, [])
+  );
+
   const onSetup = useCallback(() => {
     history.push(routes.settings.openshift.path({}));
   }, [history]);
 
   const onDeploy = useCallback(() => {
+    if (notifications.length > 0) {
+      onDeployWarningAlert.show();
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx]: To keep the logic simple, I think we can stop the process here, if there are warning or errors, without showing the `ConfirmDeployModal`.
So we can remove the `onDeployDangerAlert`. Wdyt?

File: packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx [hunk 3]
```diff
@@ -201,13 +201,31 @@ export function useDeployDropdownItems(props: Props) {
...
 
+  const onDeployWarningAlert = useGlobalAlert(
+    useCallback(({ close }) => {
+      return (
+        <Alert
+          className="pf-v5-u-mb-md"
+          variant="warning"
+          title={<>Please resolve validation errors in your workflow.</>}
+          aria-live="polite"
+          data-testid="alert-dev-mode-updating"
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx]: Please use a specific `data-testid` as this one is used by `uploadToDevModeSuccessAlert`

File: packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx [hunk 4]
```diff
@@ -201,13 +201,31 @@ export function useDeployDropdownItems(props: Props) {
     [devMode.isEnabled, props.workspaceFile.name]
   );
 
+  const onDeployWarningAlert = useGlobalAlert(
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx]:
```suggestion
  const validationWarningAlert = useGlobalAlert(
```
I would remove "deploy" from the name so we can use it for the dev mode uploading also.

File: packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx [hunk 5]
```diff
@@ -201,13 +201,31 @@ export function useDeployDropdownItems(props: Props) {
...
     history.push(routes.settings.openshift.path({}));
   }, [history]);
 
   const onDeploy = useCallback(() => {
+    if (notifications.length > 0) {
+      onDeployWarningAlert.show();
+    }
     openshift.setConfirmDeployModalOpen(true);
-  }, [openshift]);
+  }, [openshift, onDeployWarningAlert]);
```
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx]:
```suggestion
  }, [openshift, onDeployWarningAlert, notifications]);
```
As suggested by `pnpm lint` and the linting messages on this PR (just below this comment in the GH web file review)

**Review by fantonangeli — CHANGES_REQUESTED** [review]
Thanks a lot @kumaradityaraj  for this PR. If you send a message in the issue I can assign it to you.
- Could you please apply this logic to the "Upload to Dev Mode" button as well?

File: packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx
Comment (fantonangeli) [inline packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx:1]: Maybe there is an easier way we can try.
In this file at line 73 (I cannot comment unchanged lines):
```
      setCanContentBeDeployed(content.trim().length > 0 && !notifications.some((d) => d.severity === "ERROR"));
```
Can you test adding the OR condition for `WARNINGS`?
If it's workable we don't need any other alert.

**Review by fantonangeli — CHANGES_REQUESTED** [review]

**Review by fantonangeli — APPROVED** [review]

**Comment by fantonangeli** [comment]
Hi @domhanak , can you please review this PR?

**Review by domhanak — APPROVED** [review]
LGTM
