### PR TITLE
kie-issues#1264:`Management-console`: cannot reschedule job from Process Details screen

### LINKED ISSUE #1264: `Management-console`: cannot reschedule job from Process Details screen
It's impossible to reschecule a Job using the Jobs panel in the `Process Details` screen.

Browser Logs
```
Uncaught (in promise) Error: {"modalTitle":"failure","modalContent":"Reschedule of job 299508c6-e312-4f8c-ac07-742ce76e2208 failed. Message: GraphQL error: Exception while fetching data (/JobReschedule) : FAILED: RESCHEDULED JOB with id: 299508c6-e312-4f8c-ac07-742ce76e2208 errorCode:500 errorStatus:Internal Server Error errorMessage:Not able to deserialize data provided."}
    at __webpack_modules__.84621.EnvelopeBusMessageManager.callback (EnvelopeBusMessageManager.js:224:1)
    at __webpack_modules__.84621.EnvelopeBusMessageManager.receive (EnvelopeBusMessageManager.js:232:1)
    at Object.receive (EnvelopeBusMessageManager.js:89:1)
    at __webpack_modules__.35830.EnvelopeClient.receive (EnvelopeClient.js:62:1)
    at eventListener (EnvelopeClient.js:41:49)
```

Server Logs:
```
data-index              | 2024-05-21 09:55:26,379 WARN  [not.gra.exe.SimpleDataFetcherExceptionHandler] (vert.x-eventloop-thread-0) Exception while fetching data (/JobReschedule) : FAILED: RESCHEDULED JOB with id: 299508c6-e312-4f8c-ac07-742ce76e2208 errorCode:500 errorStatus:Internal Server Error errorMessage:Not able to deserialize data provided.: org.kie.kogito.index.service.DataIndexServiceException: FAILED: RESCHEDULED JOB with id: 299508c6-e312-4f8c-ac07-742ce76e2208 errorCode:500 errorStatus:Internal Server Error errorMessage:Not able to deserialize data provided.
data-index              | 	at org.kie.kogito.index.api.KogitoRuntimeCommonClient.asyncHttpResponseTreatment(KogitoRuntimeCommonClient.java:123)
data-index              | 	at org.kie.kogito.index.api.KogitoRuntimeCommonClient.lambda$sendPatchClientRequest$2(KogitoRuntimeCommonClient.java:131)
data-index              | 	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:397)
data-index              | 	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:384)
data-index              | 	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:362)
data-index              | 	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:329)
data-index              | 	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:291)
data-index              | 	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$7(HttpContext.java:507)
data-index              | 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:279)
data-index              | 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:261)
data-index              | 	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:59)
data-index              | 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
data-index              | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
data-index              | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
data-index              | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
data-index              | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
data-index              | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
data-index              | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
data-index              |
kogito-example-service  | 2024-05-21 09:55:26,343 102364b9ce55 ERROR [org.jboss.resteasy.plugins.providers.jackson:37] (executor-thread-1) RESTEASY-JACKSON000100: Not able to deserialize data provided: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.Long` from Object value (token `JsonToken.START_OBJECT`)
kogito-example-service  |  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 63] (through reference chain: org.kie.kogito.jobs.api.Job["repeatInterval"])
kogito-example-service  | 	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
kogito-example-service  | 	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1767)
kogito-example-service  | 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1541)
kogito-example-service  | 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1446)
kogito-example-service  | 	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:958)
kogito-example-service  | 	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseLong(StdDeserializer.java:949)
kogito-example-service  | 	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:575)
kogito-example-service  | 	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:550)
kogito-example-service  | 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
kogito-example-service  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
kogito-example-service  | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
kogito-example-service  | 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
kogito-example-service  | 	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2099)
kogito-example-service  | 	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1249)
kogito-example-service  | 	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.readFrom(ResteasyJackson2Provider.java:184)
kogito-example-service  | 	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:99)
kogito-example-service  | 	at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:60)
kogito-example-service  | 	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:81)
kogito-example-service  | 	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:192)
kogito-example-service  | 	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:87)
kogito-example-service  | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:116)
kogito-example-service  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
kogito-example-service  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
kogito-example-service  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
kogito-example-service  | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
kogito-example-service  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
kogito-example-service  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
kogito-example-service  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
kogito-example-service  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)
kogito-example-service  | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
kogito-example-service  | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
kogito-example-service  | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
kogito-example-service  | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
kogito-example-service  | 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
kogito-example-service  | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
kogito-example-service  | 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
kogito-example-service  | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
kogito-example-service  | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
kogito-example-service  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
kogito-example-service  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
kogito-example-service  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
kogito-example-service  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
kogito-example-service  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
kogito-example-service  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
kogito-example-service  | 	at java.base/java.lang.Thread.run(Thread.java:840)
```

Steps to reproduce:
* Run the `Compact Architecture` example
* Start a valid process instance 
* Open the instance details in `Management Console`
* Locate the Jobs Panel, verify that there's a Job instance
* On the actions kebap click on `Reschedule`
* On the `Job Reschedule` Modal, set a expiration time (click `Now`) and then click `Apply` to submit the form.
* The modal stays there without providing any feedback to the user.

### PR DESCRIPTION
**Pull request by pefernan**
Closes https://github.com/apache/incubator-kie-issues/issues/1264

### CODE REVIEW

File: packages/runtime-tools-process-enveloped-components/src/processDetails/envelope/components/ProcessDetails/ProcessDetails.tsx [hunk 1]
```diff
@@ -100,18 +100,18 @@ const ProcessDetails: React.FC<ProcessDetailsProps> = ({
...
       setIsLoading(false);
     }
   };
 
-  const getAllJobs = async (): Promise<void> => {
+  const loadJobs = useCallback(async () => {
     const jobsResponse: Job[] = await driver.jobsQuery(processDetails.id);
     jobsResponse && setJobs(jobsResponse);
-  };
+  }, [processDetails, driver]);
```
Comment (tiagobento) [inline packages/runtime-tools-process-enveloped-components/src/processDetails/envelope/components/ProcessDetails/ProcessDetails.tsx]: Hook dependency warning.

**Review by paulovmr — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]
