### PR TITLE
kie-issues#1694: Apache KIE Extended Services extension issues

### LINKED ISSUE #1684: Apache KIE Extended Services extension issues
Hello everyone,

After upgrading extension bundle to version 10.0.0 a new dependency extension named Apache KIE Extended Services introduced.

Since then, I have issues that occur on DMN file save warning me that DMN Validation failed as you can see below.

image

Could someone support on this please?

Thanks,
Vassilis

### PR DESCRIPTION
**Pull request by yesamer**
Fixes https://github.com/apache/incubator-kie-issues/issues/1684

In this PR:

The main issue is the "ambitious" management of the Extended Service Quarkus App lifecycle.
The original idea was to run the Quarkus application just after a DMN / BPMN file is opened in the editor and close it when all files are closed. Unfortunately, that implementation didn't consider the following scenarios:
- Validation checks are called when the Quarkus Application is starting up and not still ready
- Heartbeat requests are called in the same scenario described previously
- Close and opening a single DMN/BPMN file at the same moment leads the App to reach an inconsistent state, as the request of closing and starting are launched at the same moment

For that reason, I simplified the logic: the Extended Service Quarkus App is started when a DMN / BPMN file is opened for the first time and never stopped. The original idea was indeed better from a performance and resource consumption point of view, but it requires a more complex implementation.

- Updated node-fetch to 3.3.2
- `extendedServices.connectionHeartbeatIntervalinSecs` default value changed from 1 to 10. Having a heartbeat occurring every second contributed to the reported issue
- Introduced Debug logging
- Improved error message management
- Improved Configuration management
- Improved validation call body management, using the same terminology used in JIT (backend)

### CODE REVIEW

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts [hunk 1]
```diff
@@ -19,9 +19,10 @@
 
 import * as vscode from "vscode";
 
-export const enableAutoRunID: string = "extendedServices.enableAutorun";
-export const connectionHeartbeatIntervalinSecsID: string = "extendedServices.connectionHeartbeatIntervalinSecs";
-export const extendedServicesURLID: string = "extendedServices.extendedServicesURL";
+export const enableAutoRunID = "extendedServices.enableAutorun";
+export const connectionHeartbeatIntervalinSecsID = "extendedServices.connectionHeartbeatIntervalinSecs";
+export const extendedServicesURLID = "extendedServices.extendedServicesURL";
+const defaultExtendedServicesURL = "http://localhost:21345";
```
Comment (ljmotta) [inline packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: We should use the `env` value instead of hardcoding. To do so, take a look into the `build/defaultEnvJson.ts` file in some packages (e.g. `online-editor`).

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts [hunk 2]
```diff
@@ -35,65 +36,30 @@ export class Configuration {
...
-    connectionHeartbeatIntervalinSecs = fetchConnectionHeartbeatIntervalinSecs();
-  } catch (error) {
-    errorMessages.push(error.message);
+const getConfigurationPropertyValue = <T>(property: string, defaultValue: T): T => {
+  const value = vscode.workspace.getConfiguration().get(property) as T;
+  if (!value) {
+    console.warn("Property: " + property + " is missing, using the default: " + defaultValue);
   }
+  return value || defaultValue;
+};
```
Comment (ljmotta) [inline packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: I'm not sure if I followed. `T` can be a `boolean`, `number` or `string`. If is a `boolean` it will always be `true`, as it is the default value. For `number`, can't be `0`, and `string` can't be `""`? Or `value` can't be `undefined`? The `(!value)` can be tricky, please, make it explicity.

File: packages/extended-services-vscode-extension/src/requests/ValidationRequests.ts [hunk 3]
```diff
@@ -75,6 +74,14 @@ export async function validateBPMN(
...
     return validate(serviceURL, kieFile, "/jitbpmn/validate", validationresponse.parseBPMNValidationResponse);
   } catch (error) {
+    console.error(
+      "[Extended Services Extension] An error happened while trying to validate " +
+        kieFile +
+        " from serviceUrl " +
+        serviceURL +
+        ": " +
+        error
+    );
```
Comment (ljmotta) [inline packages/extended-services-vscode-extension/src/requests/ValidationRequests.ts]: You could change to `bpmnFile` as you did in another file. :wink:

The same applies for the `validateDMN`.

**Review by ljmotta — COMMENTED** [review]
@yesamer Thanks for your PR! I've made some comments inline.

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 1 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: @ljmotta It's a good point. I would like to retrieve that default value directly from the configuration here https://github.com/apache/incubator-kie-tools/pull/2802/files#diff-153d43651b25ee3120020fae349c9e8ed99ccf90aa15995784702244decf9499R91 to avoid duplication and a single place for that property value, do you think is a valid alternative should I consider?

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 2 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: > T can be a boolean, number or string. If is a boolean it will always be true, as it is the default value. For number, can't be 0, and string can't be ""

So, if the user explicitly removes the property the default value is always returned?

File: packages/extended-services-vscode-extension/src/requests/ValidationRequests.ts (hunk 3 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/requests/ValidationRequests.ts]: Done

File: packages/extended-services-vscode-extension/src/Validator.ts [hunk 4]
```diff
@@ -49,26 +49,32 @@ function createDMNDiagnostics(validationResponses: validationResponse.DMNValidat
...
-      kieFile
+      bpmnFile
     );
     return createBPMNDiagnostics(validationResponses);
   } catch (error) {
-    throw new Error("VALIDATE BPMN ERROR - " + error.message);
+    console.error("An error happened while trying to validate BPMN file: " + kieFile + " with error: " + error.message);
+    throw new Error(
+      "An error happened while trying to validate BPMN file: " + kieFile + " with error: " + error.message
+    );
```
Comment (jomarko) [inline packages/extended-services-vscode-extension/src/Validator.ts]: shouldn't we use `bpmnFile` here?

File: packages/extended-services-vscode-extension/src/Validator.ts [hunk 5]
```diff
@@ -49,26 +49,32 @@ function createDMNDiagnostics(validationResponses: validationResponse.DMNValidat
...
-      kieFile
+      dmnFile
     );
     return createDMNDiagnostics(validationResponses);
   } catch (error) {
-    throw new Error("VALIDATE DMN ERROR - " + error.message);
+    console.error("An error happened while trying to validate DMN file: " + kieFile + " with error: " + error.message);
+    throw new Error(
+      "An error happened while trying to validate DMN file: " + kieFile + " with error: " + error.message
+    );
```
Comment (jomarko) [inline packages/extended-services-vscode-extension/src/Validator.ts]: shouldn't we use `dmnFile` here?

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 1 above)
Comment (jomarko) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: yes, it is important to have an option to configure the url of extended services, users report issues about it https://github.com/apache/incubator-kie-tools/issues/2759

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts [hunk 6]
```diff
@@ -35,65 +36,31 @@ export class Configuration {
...
-  }
-
-  try {
-    connectionHeartbeatIntervalinSecs = fetchConnectionHeartbeatIntervalinSecs();
-  } catch (error) {
-    errorMessages.push(error.message);
+const getConfigurationPropertyValue = <T>(property: string, defaultValue: T): T => {
+  const value = vscode.workspace.getConfiguration().get(property) as T;
+  if (value == null) {
+    console.warn("Property: " + property + " is missing, using the default: " + defaultValue);
```
Comment (jomarko) [inline packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: `warn` should support formatting placeholders:
```
console.warn("Property: %s is missing, using the default: %s", property, defaultValue);
```

maybe even:
```
console.warn("Property: '%s' is missing, using the default: '%s'", property, defaultValue);
```

File: packages/extended-services-vscode-extension/src/Validator.ts [hunk 7]
```diff
@@ -49,26 +49,32 @@ function createDMNDiagnostics(validationResponses: validationResponse.DMNValidat
...
   try {
     const validationResponses: validationResponse.BPMNValidationResponse[] = await validationRequests.validateBPMN(
       serviceURL,
-      kieFile
+      bpmnFile
     );
     return createBPMNDiagnostics(validationResponses);
   } catch (error) {
-    throw new Error("VALIDATE BPMN ERROR - " + error.message);
+    console.error("An error happened while trying to validate BPMN file: " + kieFile + " with error: " + error.message);
```
Comment (jomarko) [inline packages/extended-services-vscode-extension/src/Validator.ts]: similar comment about formatting placeholders like `%s`

File: packages/extended-services-vscode-extension/src/Validator.ts [hunk 8]
```diff
@@ -49,26 +49,32 @@ function createDMNDiagnostics(validationResponses: validationResponse.DMNValidat
...
   try {
     const validationResponses: validationResponse.DMNValidationResponse[] = await validationRequests.validateDMN(
       serviceURL,
-      kieFile
+      dmnFile
     );
     return createDMNDiagnostics(validationResponses);
   } catch (error) {
-    throw new Error("VALIDATE DMN ERROR - " + error.message);
+    console.error("An error happened while trying to validate DMN file: " + kieFile + " with error: " + error.message);
```
Comment (jomarko) [inline packages/extended-services-vscode-extension/src/Validator.ts]: similar comment about formatting placeholders `%s`

File: packages/extended-services-vscode-extension/src/extension/extension-browser.ts [hunk 9]
```diff
@@ -67,43 +70,57 @@ function initializeVSCodeElements() {
...
 
 function startExtendedServices(): void {
+  console.debug("[Extended Services Extension] Starting Extended Service");
   try {
-    statusBarItem.show();
     configuration = fetchConfiguration();
   } catch (error) {
-    stopExtendedServices();
-    vscode.window.showErrorMessage("An error happened while trying to start the Extended Services: " + error.message);
+    console.error("[Extended Services Extension] Extension configuration is wrong: " + error.message);
```
Comment (jomarko) [inline packages/extended-services-vscode-extension/src/extension/extension-browser.ts]: `%s` comment

Comment (jomarko) [reply packages/extended-services-vscode-extension/src/extension/extension-browser.ts]: it is in whole PR, please let me know if you like that more, as it is usual shorter than manually concatenating string for the message

File: packages/extended-services-vscode-extension/src/extension/extension-main.ts [hunk 10]
```diff
@@ -43,16 +43,19 @@ let configurationWatcher: ConfigurationWatcher;
 let connection: Connection;
 let localService: LocalExtendedServices;
 
-let userDisconnected: boolean = false;
+/* Determines if the extension is corrected with the Extended Services Backend */
```
Comment (jomarko) [inline packages/extended-services-vscode-extension/src/extension/extension-main.ts]:
```suggestion
/* Determines if the extension is connected with the Extended Services Backend */
```

**Review by jomarko — COMMENTED** [review]
Thank you for the PR. I am happy we improve this extension.

### 01
Sometimes we use `extended service` (singletone) and sometimes we use `extended services` (plural).

### 02
The PR description says we never stop the extended services. Should then `extension-browser.ts` contain `const stopExtendedServicesCommandUID: string = "extended-services-vscode-extension.stopExtendedServices";` and related code? Or do we keep the option to manually stop the extended services?

No manual check done, waiting until code changes are finished.

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 2 above)
Comment (ljmotta) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: @yesamer I just considered the calls to this method. We have just 3 on this file, each one of them with T equals to `boolean`, `number` or `string`. The `if` will be `true` for the cases I listed, and we will have the log. Additionally, the return will always go to the default value for the same cases:

```sh
> "" || "my_default_value"
'my_default_value'
> 0 || 25
25
> false || true
true
```

If the `value` (has the type `T` due your casting) can have a different type, please make it explicity. Something like: `T | null` or `T | undefined`.

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 6 above)
Comment (ljmotta) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: I'm inclined to think it would be better to use template strings with the backtick:

```ts
`Property: ${property} is missing, using the default: ${defaultValue}` 
```

But this is a personal preference. As we don't have a standard for this any option is ok.

Comment (jomarko) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: I totally agree it is a personal preference. However, if there is an option, that has significant pros, like performance or security, maybe we should opt for it. Not saying there is such, just saying we have aspects that can help us to decide.

File: packages/extended-services-vscode-extension/src/Validator.ts (hunk 4 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/Validator.ts]: done

File: packages/extended-services-vscode-extension/src/Validator.ts (hunk 5 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/Validator.ts]: done

File: packages/extended-services-vscode-extension/src/extension/extension-main.ts (hunk 10 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/extension/extension-main.ts]: Done

File: packages/extended-services-vscode-extension/src/Validator.ts (hunk 8 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/Validator.ts]: Done

File: packages/extended-services-vscode-extension/src/Validator.ts (hunk 7 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/Validator.ts]: Done

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 6 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: Done, thank you both.

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 1 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: @ljmotta In the examples I checked, the env variables are accessed using the _useEnv()_ hook, but in this case, we are not managing a React app. How can I access to env variable from "plain" typescript?

File: packages/extended-services-vscode-extension/src/extension/extension-browser.ts (hunk 9 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/extension/extension-browser.ts]: done

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 1 above)
Comment (ljmotta) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: @yesamer That's true. the `defaultEnvJson` is used with the webpack transform + `fetch`, which isn't the case here. Now, you could use the webpack's `EnvironmentPlugin` to set env variables. The `online-editor` uses this approach to set some values inside the codebase. Take a look into the `online-editor/webpack.config.ts`, and search for `EnvironmentPlugin`. The `WEBPACK_REPLACE__*` values are the ones used in the codebase.

File: packages/extended-services-vscode-extension/env/index.js
Comment (ljmotta) [inline packages/extended-services-vscode-extension/env/index.js:1]: @yesamer To set `env` variables that **must** have the same values of other package, please use the available composite feature. You can take a look into the `dmn-editor/env/index.js` file, where we load multiple env files.

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 1 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: @ljmotta It should be done, there are two points to discuss:
- I added EnvironmentPlugin in both [extension-main](https://github.com/apache/incubator-kie-tools/pull/2802/files#diff-1768335dedd5cfa5e1b3830bb3b6c504f1d316dea21de55738df74f7f19c27a5R53) and [extension-browser](https://github.com/apache/incubator-kie-tools/pull/2802/files#diff-1768335dedd5cfa5e1b3830bb3b6c504f1d316dea21de55738df74f7f19c27a5R65). There's a way to define that once?
- Currently, the host and the post are parametrized, In my opinion, it would be better to have the entire URL as a parameter. E.g. http protocol is hardcoded, what if the user provides its own instance using https?

**Comment by yesamer** [comment]
@jomarko 
01
I updated all the references to use the plural form

02
Yes, the user can close the connection using a button in the bottom bar of the editor.

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 1 above)
Comment (ljmotta) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: @yesamer 
 - If you need to use in both, you can set the env variables in the `commonConfig` variable.
 - Good point. I'm not familiar on how the user set/use the Extended Services in the VS Code extension. Is it a embeded Extended Services or the user need to manually start the server? For the `extended-services-java` it will always use `http`. If the user wants to deploy it, the user will need to make the necessary adjustments to make it available through `https`.

Comment (yesamer) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: @ljmotta 
- Do you have an example for that? I mean, I added the plugin entry for both `web` and `node` https://github.com/apache/incubator-kie-tools/pull/2802/files#diff-1768335dedd5cfa5e1b3830bb3b6c504f1d316dea21de55738df74f7f19c27a5R52
To create a single entry for the plugin, which `target` and `entry` should I use?
- You're right, considering extended-services-java always uses `http`, we are safe here :)

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts [hunk 11]
```diff
@@ -19,81 +19,48 @@
...
-  } catch (error) {
-    errorMessages.push(error.message);
+const getConfigurationPropertyValue = <T>(property: string, defaultValue: T): T => {
+  const value: T | null = vscode.workspace.getConfiguration().get(property) as T;
+  if (value == null) {
+    console.warn(`Property: ${property} is missing, using the default: ${defaultValue}`);
+    value == defaultValue;
   }
+  return value;
+};
```
Comment (ljmotta) [inline packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: @yesamer I just have one comment related to this method, here is a suggestion of improvement. Also, I'm fixing two things here, the first double equals (`==`) to triple equals, and the second double equals should be an attribution.

```suggestion
// Place on top of the file or on another file
// I don't think this is a suitable name, it's just to exemplify
type Property = string | number | boolean

const getConfigurationPropertyValue = <T extends Property | null>(property: string, defaultValue: T): T => {
  const value = vscode.workspace.getConfiguration().get(property) as T;
  if (value === null) {
    console.warn(`Property: ${property} is missing, using the default: ${defaultValue}`);
    value = defaultValue;
  }
  return value;
};
```

**Comment by jomarko** [comment]
### Closing the model file
Hi @yesamer or anyone, should closing the dmn/bpmn file to close also the message in problems tab? Currently it seems the problems tab is not cleared if model file is closed. Is that an expected behavior?
Screenshot 2025-01-03 132148

### Disable Autorun and use URL
Once I disabled the autorun and started extended services as `pnpm -F @kie-tools/extended-services-java start` I was not able to connect VSCode extended services extension to the extended services instance.
Screenshot 2025-01-03 133741

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 11 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts]: @ljmotta Thank you, I committed your suggested change, I'll update the comment and the property name

**Comment by yesamer** [comment]
@jomarko 
/cc @ljmotta @tiagobento 

I'm double-checking the behavior you reported. However, I'm not fully aware of the expected behavior of this feature, so my goal is to implement a minimal use-case scenario for this extension.

**Comment by yesamer** [comment]
@jomarko I fixed the first use case you reported,  **Closing the model file**.
The second scenario, **Disable Autorun and use URL**, works correctly in my local

https://github.com/user-attachments/assets/4887c612-2ed4-4534-a32c-152f6efa45b6

**Comment by ljmotta** [comment]
@jomarko I'm not sure if using `0.0.0.0` is correct here, please try with `localhost`.

@yesamer Please let me kwown when the PR is ready for another review.

**Comment by yesamer** [comment]
@ljmotta Yes, please :)

**Review by ljmotta — APPROVED** [review]
@yesamer Thanks for your patience, LGTM!

**Comment by tiagobento** [comment]
Deferring my review to @jomarko, feel free to merge when approved by him and green! Thanks for the great effort here.

File: packages/extended-services-vscode-extension/src/Validator.ts [hunk 12]
```diff
@@ -49,26 +49,28 @@ function createDMNDiagnostics(validationResponses: validationResponse.DMNValidat
...
     const validationResponses: validationResponse.BPMNValidationResponse[] = await validationRequests.validateBPMN(
       serviceURL,
-      kieFile
+      bpmnFile
     );
     return createBPMNDiagnostics(validationResponses);
   } catch (error) {
-    throw new Error("VALIDATE BPMN ERROR - " + error.message);
+    console.error(`An error occured while trying to validate DMN file: ${bpmnFile} with error: ${error.message}`);
+    throw new Error(`An error occured while trying to validate DMN file: ${bpmnFile} with error: ${error.message}`);
```
Comment (jomarko) [inline packages/extended-services-vscode-extension/src/Validator.ts]:
```suggestion
    console.error(`An error occured while trying to validate BPMN file: ${bpmnFile} with error: ${error.message}`);
    throw new Error(`An error occured while trying to validate BPMN file: ${bpmnFile} with error: ${error.message}`);
```

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts [hunk 13]
```diff
@@ -19,81 +19,53 @@
...
-    errorMessages.push(error.message);
-  }
-
-  try {
-    connectionHeartbeatIntervalinSecs = fetchConnectionHeartbeatIntervalinSecs();
-  } catch (error) {
-    errorMessages.push(error.message);
+const getConfigurationPropertyValue = <T extends ConfigurationProperty | null>(
+  property: string,
+  defaultValue: T
```
Comment (jomarko) [inline packages/extended-services-vscode-extension/src/configurations/Configuration.ts:52]: Why do we need to have also `defaultValue` parameter here? the three configurations related to this PR in `extended-services-vscode-extension/package.json`. Do we use `getConfigurationPropertyValue` also for loading configurations that do not have default value specified?

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts [hunk 14]
```diff
@@ -19,81 +19,53 @@
...
-    extendedServicesURL = fetchExtendedServicesURL();
-  } catch (error) {
-    errorMessages.push(error.message);
-  }
+export function fetchConfiguration(): Configuration {
+  const enableAutoRun = getConfigurationPropertyValue<boolean>(enableAutoRunID, true);
+  const connectionHeartbeatIntervalInSecs = getConfigurationPropertyValue<number>(
+    connectionHeartbeatIntervalInSecsID,
+    10
+  );
```
Comment (jomarko) [inline packages/extended-services-vscode-extension/src/configurations/Configuration.ts:67]: related to question above, to me it seems that `true` and `10` and duplicated values that are already set in package.json what is vulnerable to get out of sync and then potentially make debugging and solving issues more difficult

File: packages/extended-services-vscode-extension/src/extension/extension-browser.ts [hunk 15]
```diff
@@ -67,60 +70,71 @@ function initializeVSCodeElements() {
...
   const bpmnFiles: KieFile[] = await kiefilesfetcher.findActiveKieFiles([kiefilesfetcher.bpmnDocumentFilter]);
   const dmnFiles: KieFile[] = await kiefilesfetcher.findActiveKieFiles([kiefilesfetcher.dmnDocumentFilter]);
 
   for (const bpmnFile of bpmnFiles) {
     try {
-      const bpmnDiagnostics: vscode.Diagnostic[] = await validator.validateBPMN(
-        configuration.extendedServicesURL,
-        bpmnFile
-      );
+      console.debug(`[Extended Services Extension] Validating DMN file: ${bpmnFile.uri.path}`);
```
Comment (jomarko) [inline packages/extended-services-vscode-extension/src/extension/extension-browser.ts]:
```suggestion
      console.debug(`[Extended Services Extension] Validating BPMN file: ${bpmnFile.uri.path}`);
```

File: packages/extended-services-vscode-extension/src/requests/PingRequest.ts [hunk 16]
```diff
@@ -23,6 +23,7 @@ export async function ping(extendedServicesURL: URL): Promise<pingresponse.PingR
   const url = new URL("/ping", extendedServicesURL);
 
   try {
+    console.debug("[Extended Services Extension] Pinging: " + url.toString());
```
Comment (jomarko) [inline packages/extended-services-vscode-extension/src/requests/PingRequest.ts]: maybe we could improve the variable name. what is your opinion about `extendedServicesPingURL`?

**Review by jomarko — COMMENTED** [review]
Thank you @yesamer , I put some comments to code inline.

One question is also what is the difference of `extension-main.ts` and `extension-browser.ts` as their content seems to be very similar.

My biggest problem is there is no vsix file produced by the PR, or am I searching inappropriately? I tried to build the extension locally: `pnpm -F extended-services-vscode-extension... build:prod` however in that case it seems to not work properly, I would like to use vsix produced by the CI.
Screenshot 2025-01-16 075703

File: packages/extended-services-vscode-extension/src/requests/PingRequest.ts (hunk 16 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/requests/PingRequest.ts]: @jomarko Done

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 13 above)
Comment (yesamer) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts:52]: @jomarko Those configuration parameters are loaded from the extension's setting, and these values can be accidentally erased by the user. Despite we could argue this is a low-probability scenario, I guess it's worth ensuring the extension can effectively work in most of the scenarios.

Screenshot 2025-01-16 at 08 13 40

Does make sense?

Comment (jomarko) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts:52]: ok, I understand now, thank you

File: packages/extended-services-vscode-extension/src/configurations/Configuration.ts (hunk 14 above)
Comment (jomarko) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts:67]: resolved because of https://github.com/apache/incubator-kie-tools/pull/2802#discussion_r1917863297

Comment (yesamer) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts:67]: @jomarko  You're right, I had (and still have) the same concern, but honestly, I didn't find a solution to avoid this duplication. The ideal solution should be to retrieve the values from the package.json, I have to admit I didn't investigate if this is possible or not.

Comment (yesamer) [reply packages/extended-services-vscode-extension/src/configurations/Configuration.ts:67]: @jomarko ^^ :)

**Review by jomarko — APPROVED** [review]
Thank you @yesamer. Using the VSIX produced by the CI I was able to:
- use extended-services extension in the auto run mode
- use extended-services extension connecting to services started in standalone terminal

Approving the PR, however opening two points that are not blocking from the merge.

### Extension info
Seems to show old information, probably it needs to be first pushed to marketplace? I do not know. Notice the ping interval value.
image

### Icon
Extended-services liveness icon indicator (bottom right corner) is shown from my point of view in 'difficult to understand' way. From my point of view, in separate ticket it would be worth to do a simplification. Here is my proposal, however not sure what is opinion of others.

Once extended-services extension is installed:
- we either show connection live icon
- or connection not live icon
- there should be no case icon is missing

**Comment by yesamer** [comment]
@jomarko Thank you for the review, it's indeed strange the Extension info is not updated. I checked, and the default value is correct in the package.json.
Regarding your proposal with the ICON, I agree with you that should be revisited, together with other components.
We agreed with @tiagobento to invest more time on this extension in the future, based on our priorities, so it makes sense to keep track of all elements/behavior you already found during this PR review, and open a discussion of its requirements
